### ISSUE TITLE
TypeError: sigterm_handler() takes 0 positional arguments but 2 were given

### ISSUE THREAD

**Issue by DoDzilla-ai** [dateutil/dateutil#1003]
I am trying to find the number of dates inside a CSV file with this code:
```
    def is_date(val):
        count = 0
        for v in val:
            try:
                parse(str(v))
                count += 1
            except ValueError:
                pass
            except OverflowError:
                pass
        return count
```
I don't know what is changed but this was working without a problem in the past. I am running this as a multiprocessed function. If I use the **spawn** method I don't encounter any error but if I use **fork** method I am getting this error:
```
2020-01-30 12:37:54 - root         - ERROR    - Traceback (most recent call last):
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 655, in parse
    ret = self._build_naive(res, default)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1238, in _build_naive
    if cday > monthrange(cyear, cmonth)[1]:
  File "/home/dodzilla/anaconda3/envs/aiclap-backend/lib/python3.6/calendar.py", line 123, in monthrange
    raise IllegalMonthError(month)
calendar.IllegalMonthError: bad month number 0; must be 1-12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dodzilla/aiclap-backend/components_with_adapter/column_type_specifier.py", line 68, in processCols
    date_check_list = int(ColumnTypeSpecifier.is_date(cols[:limit]))
  File "/home/dodzilla/aiclap-backend/components_with_adapter/column_type_specifier.py", line 28, in is_date
    parse(str(v))
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 657, in parse
    six.raise_from(ParserError(e.args[0] + ": %s", timestr), e)
TypeError: unsupported operand type(s) for +: 'int' and 'str'

2020-01-30 12:37:54 - root         - ERROR    - Traceback (most recent call last):
  File "/home/dodzilla/aiclap-backend/components_with_adapter/column_type_specifier.py", line 68, in processCols
    date_check_list = int(ColumnTypeSpecifier.is_date(cols[:limit]))
  File "/home/dodzilla/aiclap-backend/components_with_adapter/column_type_specifier.py", line 28, in is_date
    parse(str(v))
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 646, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 725, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 207, in split
    return list(cls(s))
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 196, in __next__
    token = self.get_token()
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 148, in get_token
    token += nextchar
TypeError: sigterm_handler() takes 0 positional arguments but 2 were given
```
and the program hangs there. It actually runs for a while but for some reason after some try/except it hangs. This is how I start the multiprocessing:
```
from multiprocessing import cpu_count, get_context
n_jobs = 8
ctx = get_context('fork')
            with ctx.Pool(n_jobs) as p:
                if isinstance(df, dict):
                    for key, value in df.items():
                        new_df = p.imap(ColumnTypeSpecifier.processCols, [value[df_cols] for df_cols in value])
                        new_df = pd.concat(new_df, axis=1)
```
I can't share neither the data nor the full code but this should give you some insight.
**Versions:**
python==3.6
python-dateutil==2.8.1
six==1.12.0
distributed==2.9.0

Full-traceback:
```
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 655, in parse
    ret = self._build_naive(res, default)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1238, in _build_naive
    if cday > monthrange(cyear, cmonth)[1]:
  File "/home/dodzilla/anaconda3/envs/my_project/lib/python3.6/calendar.py", line 123, in monthrange
    raise IllegalMonthError(month)
calendar.IllegalMonthError: bad month number 95; must be 1-12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 68, in processCols
    date_check_list = int(ColumnTypeSpecifier.is_date(cols[:limit]))
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 28, in is_date
    parse(str(v))
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 657, in parse
    six.raise_from(ParserError(e.args[0] + ": %s", timestr), e)
TypeError: unsupported operand type(s) for +: 'int' and 'str'

2020-01-30 12:37:54 - root         - ERROR    - Traceback (most recent call last):
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 655, in parse
    ret = self._build_naive(res, default)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1238, in _build_naive
    if cday > monthrange(cyear, cmonth)[1]:
  File "/home/dodzilla/anaconda3/envs/my_project/lib/python3.6/calendar.py", line 123, in monthrange
    raise IllegalMonthError(month)
calendar.IllegalMonthError: bad month number 85; must be 1-12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 68, in processCols
    date_check_list = int(ColumnTypeSpecifier.is_date(cols[:limit]))
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 28, in is_date
    parse(str(v))
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 657, in parse
    six.raise_from(ParserError(e.args[0] + ": %s", timestr), e)
TypeError: unsupported operand type(s) for +: 'int' and 'str'

2020-01-30 12:37:54 - root         - ERROR    - Traceback (most recent call last):
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 655, in parse
    ret = self._build_naive(res, default)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1238, in _build_naive
    if cday > monthrange(cyear, cmonth)[1]:
  File "/home/dodzilla/anaconda3/envs/my_project/lib/python3.6/calendar.py", line 123, in monthrange
    raise IllegalMonthError(month)
calendar.IllegalMonthError: bad month number 95; must be 1-12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 68, in processCols
    date_check_list = int(ColumnTypeSpecifier.is_date(cols[:limit]))
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 28, in is_date
    parse(str(v))
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 657, in parse
    six.raise_from(ParserError(e.args[0] + ": %s", timestr), e)
TypeError: unsupported operand type(s) for +: 'int' and 'str'

2020-01-30 12:37:54 - root         - ERROR    - Traceback (most recent call last):
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 655, in parse
    ret = self._build_naive(res, default)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1238, in _build_naive
    if cday > monthrange(cyear, cmonth)[1]:
  File "/home/dodzilla/anaconda3/envs/my_project/lib/python3.6/calendar.py", line 123, in monthrange
    raise IllegalMonthError(month)
calendar.IllegalMonthError: bad month number 2000062; must be 1-12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 68, in processCols
    date_check_list = int(ColumnTypeSpecifier.is_date(cols[:limit]))
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 28, in is_date
    parse(str(v))
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 657, in parse
    six.raise_from(ParserError(e.args[0] + ": %s", timestr), e)
TypeError: unsupported operand type(s) for +: 'int' and 'str'

2020-01-30 12:37:54 - root         - ERROR    - Traceback (most recent call last):
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 655, in parse
    ret = self._build_naive(res, default)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1238, in _build_naive
    if cday > monthrange(cyear, cmonth)[1]:
  File "/home/dodzilla/anaconda3/envs/my_project/lib/python3.6/calendar.py", line 123, in monthrange
    raise IllegalMonthError(month)
calendar.IllegalMonthError: bad month number 95; must be 1-12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 68, in processCols
    date_check_list = int(ColumnTypeSpecifier.is_date(cols[:limit]))
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 28, in is_date
    parse(str(v))
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 657, in parse
    six.raise_from(ParserError(e.args[0] + ": %s", timestr), e)
TypeError: unsupported operand type(s) for +: 'int' and 'str'

2020-01-30 12:37:54 - root         - ERROR    - Traceback (most recent call last):
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 655, in parse
    ret = self._build_naive(res, default)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1238, in _build_naive
    if cday > monthrange(cyear, cmonth)[1]:
  File "/home/dodzilla/anaconda3/envs/my_project/lib/python3.6/calendar.py", line 123, in monthrange
    raise IllegalMonthError(month)
calendar.IllegalMonthError: bad month number 95; must be 1-12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 68, in processCols
    date_check_list = int(ColumnTypeSpecifier.is_date(cols[:limit]))
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 28, in is_date
    parse(str(v))
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 657, in parse
    six.raise_from(ParserError(e.args[0] + ": %s", timestr), e)
TypeError: unsupported operand type(s) for +: 'int' and 'str'

/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py:1218: UnknownTimezoneWarning: tzname GM identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  category=UnknownTimezoneWarning)
2020-01-30 12:37:54 - root         - ERROR    - Traceback (most recent call last):
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 655, in parse
    ret = self._build_naive(res, default)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1238, in _build_naive
    if cday > monthrange(cyear, cmonth)[1]:
  File "/home/dodzilla/anaconda3/envs/my_project/lib/python3.6/calendar.py", line 123, in monthrange
    raise IllegalMonthError(month)
calendar.IllegalMonthError: bad month number 79; must be 1-12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 68, in processCols
    date_check_list = int(ColumnTypeSpecifier.is_date(cols[:limit]))
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 28, in is_date
    parse(str(v))
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 657, in parse
    six.raise_from(ParserError(e.args[0] + ": %s", timestr), e)
TypeError: unsupported operand type(s) for +: 'int' and 'str'

2020-01-30 12:37:54 - root         - ERROR    - Traceback (most recent call last):
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 655, in parse
    ret = self._build_naive(res, default)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1238, in _build_naive
    if cday > monthrange(cyear, cmonth)[1]:
  File "/home/dodzilla/anaconda3/envs/my_project/lib/python3.6/calendar.py", line 123, in monthrange
    raise IllegalMonthError(month)
calendar.IllegalMonthError: bad month number 0; must be 1-12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 68, in processCols
    date_check_list = int(ColumnTypeSpecifier.is_date(cols[:limit]))
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 28, in is_date
    parse(str(v))
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 657, in parse
    six.raise_from(ParserError(e.args[0] + ": %s", timestr), e)
TypeError: unsupported operand type(s) for +: 'int' and 'str'

2020-01-30 12:37:54 - root         - ERROR    - Traceback (most recent call last):
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 655, in parse
    ret = self._build_naive(res, default)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1238, in _build_naive
    if cday > monthrange(cyear, cmonth)[1]:
  File "/home/dodzilla/anaconda3/envs/my_project/lib/python3.6/calendar.py", line 123, in monthrange
    raise IllegalMonthError(month)
calendar.IllegalMonthError: bad month number 0; must be 1-12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 68, in processCols
    date_check_list = int(ColumnTypeSpecifier.is_date(cols[:limit]))
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 28, in is_date
    parse(str(v))
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 657, in parse
    six.raise_from(ParserError(e.args[0] + ": %s", timestr), e)
TypeError: unsupported operand type(s) for +: 'int' and 'str'

2020-01-30 12:37:54 - root         - ERROR    - Traceback (most recent call last):
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 68, in processCols
    date_check_list = int(ColumnTypeSpecifier.is_date(cols[:limit]))
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 28, in is_date
    parse(str(v))
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 646, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 725, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 207, in split
    return list(cls(s))
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 196, in __next__
    token = self.get_token()
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 148, in get_token
    token += nextchar
TypeError: sigterm_handler() takes 0 positional arguments but 2 were given
2020-01-30 12:37:54 - root         - ERROR    - Traceback (most recent call last):
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 68, in processCols
    date_check_list = int(ColumnTypeSpecifier.is_date(cols[:limit]))
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 28, in is_date
    parse(str(v))
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 646, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 724, in _parse
    res = self._result()
TypeError: sigterm_handler() takes 0 positional arguments but 2 were given
2020-01-30 12:37:54 - root         - ERROR    - Traceback (most recent call last):
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 68, in processCols
    date_check_list = int(ColumnTypeSpecifier.is_date(cols[:limit]))
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 28, in is_date
    parse(str(v))
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 646, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 872, in _parse
    if not info.validate(res):
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 391, in validate
    if ((res.tzoffset == 0 and not res.tzname) or
TypeError: sigterm_handler() takes 0 positional arguments but 2 were given



2020-01-30 12:37:54 - root         - ERROR    - Traceback (most recent call last):
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 68, in processCols
    date_check_list = int(ColumnTypeSpecifier.is_date(cols[:limit]))
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 28, in is_date
    parse(str(v))
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 646, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 725, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 207, in split
    return list(cls(s))
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 72, in __init__
    if isinstance(instream, text_type):
TypeError: sigterm_handler() takes 0 positional arguments but 2 were given
2020-01-30 12:37:54 - root         - ERROR    - Traceback (most recent call last):
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 68, in processCols
    date_check_list = int(ColumnTypeSpecifier.is_date(cols[:limit]))
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 28, in is_date
    parse(str(v))
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 646, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 725, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 207, in split
    return list(cls(s))
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 196, in __next__
    token = self.get_token()
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 112, in get_token
    nextchar = self.instream.read(1)
TypeError: sigterm_handler() takes 0 positional arguments but 2 were given


2020-01-30 12:37:54 - root         - ERROR    - Traceback (most recent call last):
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 68, in processCols
    date_check_list = int(ColumnTypeSpecifier.is_date(cols[:limit]))
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 28, in is_date
    parse(str(v))
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 643, in parse
    default = datetime.datetime.now().replace(hour=0, minute=0,
TypeError: sigterm_handler() takes 0 positional arguments but 2 were given

2020-01-30 12:37:54 - root         - ERROR    - Traceback (most recent call last):
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 655, in parse
    ret = self._build_naive(res, default)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1238, in _build_naive
    if cday > monthrange(cyear, cmonth)[1]:
  File "/home/dodzilla/anaconda3/envs/my_project/lib/python3.6/calendar.py", line 123, in monthrange
    raise IllegalMonthError(month)
calendar.IllegalMonthError: bad month number 0; must be 1-12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 68, in processCols
    date_check_list = int(ColumnTypeSpecifier.is_date(cols[:limit]))
  File "/home/dodzilla/my_project/components_with_adapter/column_type_specifier.py", line 28, in is_date
    parse(str(v))
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/dodzilla/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 657, in parse
    six.raise_from(ParserError(e.args[0] + ": %s", timestr), e)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

**Comment by nanonyme** [comment]
The middle exception in stack trace is effectively duplicate of https://github.com/dateutil/dateutil/issues/981
