### ISSUE TITLE
rrule-parser fails on non-standard X-RELATIVE key

### ISSUE THREAD

**Issue by Konfekt** [dateutil/dateutil#1031]
This issue asks for support for parsing the ` X-RELATIVE `  key in  `RRULE` strings. 

Currently, for example, the following ICS file

```ics
BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VTODO
DUE;TZID=Europe/Berlin:20200516T100000
SUMMARY:Test
DESCRIPTION:Test
CLASS:PRIVATE
LAST-MODIFIED:20200419T131234Z
RRULE:FREQ=MONTHLY;INTERVAL=3;X-RELATIVE=1
STATUS:NEEDS-ACTION
UID:4283265
END:VTODO
END:VCALENDAR
```

 would produce this error:

```python
Failed to read entry /home/konfekt/.local/share/vdirsyncer/todo/all/task.ics.
Traceback (most recent call last):
  File "/home/konfekt/.local/lib/python3.6/site-packages/todoman/model.py", line 1007, in update_cache
    self.cache.add_vtodo(component, entry_path)
  File "/home/konfekt/.local/lib/python3.6/site-packages/todoman/model.py", line 651, in add_vtodo
    self._serialize_rrule(todo, 'rrule'),
  File "/home/konfekt/.local/lib/python3.6/site-packages/todoman/model.py", line 584, in _serialize_rrule
    return rrule.to_ical().decode()
  File "/home/konfekt/.local/lib/python3.6/site-packages/icalendar/prop.py", line 676, in to_ical
    typ = self.types[key]
  File "/home/konfekt/.local/lib/python3.6/site-packages/icalendar/caselessdict.py", line 42, in __getitem__
    return super(CaselessDict, self).__getitem__(key.upper())
KeyError: 'X-RELATIVE'
```

This issue has been forwarded from https://github.com/pimutils/todoman/issues/386

**Comment by Konfekt** [comment]
Perhaps the [datestuff](https://github.com/justanr/datestuff) library as discussed in https://github.com/dateutil/dateutil/issues/431 could help here.

**Comment by ffe4** [comment]
As it is a non-standard key, it would be great if you could tell us how you would expect the `RRULE` to be handled, i.e. what it should return. It would also be good to know where you exported the ICS file from.

One thing I noticed in your example is that there was no `DTSTART` property defined for your `VTODO` component. According to [RFC 5545](https://tools.ietf.org/html/rfc5545#section-3.8.2.4), "this property is REQUIRED in all types of recurring calendar components that specify the "RRULE" property." In `dateutil`, this property defaults to `datetime.now()` if it is not specified. Depending on what the `X-Relative` key is supposed to do, this might require downstream packages to support non-standard keys as well to supply the proper `DTSTART`.

If non-standard keys are out there, we should probably consider handling them in some way. If this key is commonly supported in other applications it might be worth supporting here as well.

**Comment by Konfekt** [comment]
I am sorry, I stripped what did not seem relevant to the initial issue.
Yes, a DTSTART field is there, let me try another minimal example.

```
BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VTODO
UID:4283265
DTSTART;TZID=Europe/Paris:20190318T000000
DUE;TZID=Europe/Berlin:20200516T100000
SUMMARY:Test
CLASS:PRIVATE
RRULE:FREQ=MONTHLY;INTERVAL=3;X-RELATIVE=1
STATUS:NEEDS-ACTION
DTSTAMP:20200419T122133Z
END:VTODO
END:VCALENDAR
```

The field X-RELATIVE was added for a recurrent task that starts, say on every first Monday of a month by a Nextcloud server.
It is hard to find it documented anywhere.
Perhaps

https://github.com/nextcloud/server/commit/31e1c15db722d8363ceab6c97da14d703badb4f5

gives a hint.
In the end, it might just be a tag that Nextcloud uses to denote a date relative to something; whatever it is.

**Comment by Konfekt** [comment]
If this key is created by Nextcloud, then perhaps its users can [help](https://help.nextcloud.com/t/meaning-x-relative-key-in-rrdate-field/78672).

**Comment by ffe4** [comment]
Thank you for trying to clear this up.

I have skimmed the RFC again, and I think this might actually a bug, since we should already be ignoring the key according to the RFC. Quote:
> Applications MUST ignore x-param and iana-param values they don't recognize.

If you do not need the RRULE, or the key does not have any effect on the result, this would solve your issue, but I think implementing experimental features from other applications in `dateutil` would only be warranted if they were widespread, which does not seem to be the case here. It would be nice if we could still give users the option to handle unknown keys somehow, but I'm not sure whether there's a good way to do that.

**Comment by Konfekt** [comment]
> Applications MUST ignore x-param and iana-param values they don't recognize.

Yes, this sounds sensible; to me, `X-RELATIVE` seems to be a key giving additional information that only Nextcloud can interpret and is best ignored otherwise. 
I would be glad if dateutil could do so.

**Comment by mattlaabs** [comment]
X-RELATIVE is set by aCalendar (which I am the developer of) to indicate that a recurring task is meant to repeat relative to the date when it is completed, and not according to a fixed schedule (which is the only mechanism known by the ical standard). Example use-case: you water your plants every 8 days, but now are 5 days late. With this setting on, the next occurrence will be again after 8 days instead of after only 3 more days with the regular fixed cycle.

**Comment by ffe4** [comment]
Thank you @mattlaabs for clearing this up!

Since this relies on the date of completion, it has to be done outside `dateutil`, but can easily be implemented by calling the `replace()` method on `rrule`, replacing the `dtstart` attribute with the date of completion. I think we could add a flag to the `rrulestr()` function, similar to `fuzzy_with_tokens` in the `parser` module, that returns non-standard keys to enable users to implement these kinds of cases.

It seems ignoring unknown `X-` parameters should be the default behavior. Since someone could be relying on the error for validating RRULE strings, it might be preferable to provide a `strict` parsing flag defaulting to `True` for now and change the default in the next major release.
