### ISSUE TITLE
unknown string format issue

### ISSUE THREAD

**Issue by jfabiani** [dateutil/dateutil#1061]
this works:
parser.parse('June 19,2020,10:37 pm')
datetime.datetime(2020, 6, 19, 22, 37)

but this does not work:
parser.parse('April 8,2020,12:00 am')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 649, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: April 8,2020,12:00 am

but it will work if I put a space in front of the '12:00'

**Comment by ffe4** [comment]
The tokens are split differently by the `_timelex.split` method, which seems to have issues with the commas.  I have not looked at how the `_timelex` class works yet, so I am not sure whether this can be changed easily without breaking something else, but if you know that adding a space after the commas (or replacing them with spaces) will work for all the date formats you are expecting, that might be a viable workaround. Where did you encounter this format?

I suspect the parsing difference might be due to the logic recognizing 19 as unambiguously the date of the month, but being unsure about the 8.
```python
from dateutil.parser._parser import _timelex
_timelex.split('June 19,2020,10:37 pm')
# ['June', ' ', '19.2020', ',', '10', ':', '37', ' ', 'pm']
_timelex.split('April 8,2020,12:00 am')
# ['April', ' ', '8', ',', '2020.12', ':', '00', ' ', 'am']
```

Either way, since the token after `'2020.12'` is a colon, it gets interpreted as a an hour and cast to `int` by `_parse_numeric_token`, which then leads to an error in `_ampm_valid` since `not 0 <= 2020 <= 12`. It works if you put a space after the comma because then `'2020.12'` gets split up into separate tokens and `'12'` becomes the token before the colon instead.

**Comment by jfabiani** [comment]
The data is coming from a website downloaded csv file.  It does open in excell correctly.  However, I needed the data in a postgresql database and that required some changes to the data date fields.  I in fact used .replace('',' ') as a work around.
