### ISSUE TITLE
Incorrect value parsed as ISO date

### ISSUE THREAD

**Issue by janos-gonye** [dateutil/dateutil#1074]
**Version:**
`Python`: 3.8.2
`dateutil`: 2.8.1

**Description:**
The `dateutil.parse.isoparse` function parses an incorrect ISO string.

```python
from dateutil import parser


dt = parser.isoparse("20200728121240")
# Expected: `ValueError`
# What happens is:
print(dt)
# 2020-07-28 21:24:00
# datetime.datetime(2020, 7, 28, 21, 24)
```

**Expected Behavior:**
`ValueError` raised with a proper error message.

**Comment by ffe4** [comment]
Looking at the [documentation](https://dateutil.readthedocs.io/en/stable/parser.html#dateutil.parser.isoparse), the following seems to be the root of the issue:

> the date and time portions are separated by a single character separator, which is T in the official standard

Note the different output of `parse` and `isoparse`:
```pycon
>>> isoparse("20200728121240")
datetime.datetime(2020, 7, 28, 21, 24)
>>> parse("20200728121240")
datetime.datetime(2020, 7, 28, 12, 12, 40)
```

`isoparse` seems to interpret the `1` after the date as a non-standard separator. Since there is only a single character left at the end, this should probably be a sign that there was an issue with the format, as single character time components are not listed as supported.

**Comment by immanuelfodor** [comment]
I have the same problem, shouldn't it be more obvious that there is a parsing error?

**Comment by immanuelfodor** [comment]
parsing error ~ potentially misinterpreted parse

**Comment by ffe4** [comment]
@immanuelfodor the last sentence in my previous comment was meant as a note regarding a possible implementation of a check for such an error. While `isoparse` does not guarantee that invalid strings will fail if they encode a valid date (see warning in the documentation), the current behavior seems undesirable.

However, seeing `isoparse` does not promise strictness, it seems unsuited for date validation. With that in mind, I wonder whether it should be used in a context where non-ISO dates will be encountered in the first place.

**Comment by immanuelfodor** [comment]
IMHO the main problem is with user input when the frontend should send ISO formatted datetime (e.g., from AJAX) but the user tampers with the format and tries to handcraft a prepared message for the backend API. But you seem to be right:
> However, seeing isoparse does not promise strictness, it seems unsuited for date validation

**Comment by immanuelfodor** [comment]
> As of version 2.7.0, the strictness of the parser should not be considered a stable part of the contract. 

Well, my only question is: why does `isoparse` not promise strictness?

**Comment by ffe4** [comment]
@immanuelfodor It seems `isoparse()` originated from issue #424 as an inverse of `isoformat()` (also see PR #489). Note the emphasis in the original issue:
> If you _know_ you've got an iso8601 date, [...]

**Comment by pganssle** [comment]
I think that `isoparse` is intended to be strict, but the precise form of the strictness is not guaranteed because the spec is limited or ambiguous in some ways, and `datetime.isoformat()` exceeds it at times.

The long term goal of the function was to default to accepting some reasonable subset of the extensions and eventually allowing them to be turned off for people desiring greater strictness.

In this case there seem to be two issues: the separator is missing and the `1` is interpreted as a separator, and the last component is just `0` and not `00`. The first one I think we can't change the default because `some_datetime.isoformat(sep="1")` could be used to specify that separator, but I think you can make `isoparse` more strict by specifying a separator, like: `parser.isoparser("T").isoparse(...)`.

If the second issue (HHMMS instead of HHMMSS) is out of spec, we should fix that.

**Comment by immanuelfodor** [comment]
> If the second issue (HHMMS instead of HHMMSS) is out of spec

And it would be great as middle ground solution if only the separators are missing. When the 1 is interpreted as a separator, the HHMMS part would raise a ValueError by missing one more character from the datetime string.

**Comment by pganssle** [comment]
This is indeed out of spec, so we can at least fix `parser.isoparse` allowing the hours or minutes component to be a single digit.

I've opened PR #1077.

**Comment by weatherfrog** [comment]
Bug is still there two years later:

```
>>> d1 = "202001012223"
>>> d2 = "202001012323"
>>> dateutil.parser.isoparse(d1)
datetime.datetime(2020, 1, 1, 22, 3)
>>> dateutil.parser.isoparse(d2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rg/src/pyapi/.nox/devel-3-9/lib/python3.9/site-packages/dateutil/parser/isoparser.py", line 37, in func
    return f(self, str_in, *args, **kwargs)
  File "/Users/rg/src/pyapi/.nox/devel-3-9/lib/python3.9/site-packages/dateutil/parser/isoparser.py", line 146, in isoparse
    return datetime(*components)
ValueError: hour must be in 0..23
```

Why has @pganssle 's PR not been merged?
