### ISSUE TITLE
Bug: parse breaks when presented with a date in this format: %Y-%m-%d %H:%M:%S %Z

### ISSUE THREAD

**Issue by c3101** [dateutil/dateutil#1117]
dateutil.parser._parser.ParserError: Unknown string format: 2021-04-19 09:00:42 utc

This seems to parse it:
datetime.datetime.strptime(Date, "%Y-%m-%d %H:%M:%S %Z")

**Comment by samamorgan** [comment]
The main issue appears to be lowercase timezone.

```python
>>> from dateutil.parser import parse
>>> parse("2021-04-19 09:00:42")     
datetime.datetime(2021, 4, 19, 9, 0, 42)

>>> parse("2021-04-19 09:00:42 Z") 
datetime.datetime(2021, 4, 19, 9, 0, 42, tzinfo=tzutc())

>>> parse("2021-04-19 09:00:42 utc") 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\site-packages\dateutil\parser\_parser.py", line 1374, in parse    
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\site-packages\dateutil\parser\_parser.py", line 649, in parse     
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: 2021-04-19 09:00:42 utc

>>> parse("2021-04-19 09:00:42 UTC") 
datetime.datetime(2021, 4, 19, 9, 0, 42, tzinfo=tzutc())
```

**Comment by pganssle** [comment]
You can also pass `tzinfos={"utc": datetime.timezone.utc}` to the parser. Not really sure why we don't interpret `utc` as `UTC`, though.
