### ISSUE TITLE
2.8.2: pytest amd tox are failing

### ISSUE THREAD

**Issue by kloczek** [dateutil/dateutil#1144]
Just checked https://github.com/dateutil/dateutil/blob/master/.github/workflows/validate.yml and looks like in CI tox is executed by `python -m tox` instead using shell script `tox`. It is one difference of unix pytest or tox that way because when those modules are executest that way python adds to `sys.path` upfront current path.
In other words it is tested source tree and  using that methodology os not possible to test what is installed by `setup.py install --root </install/prefix>`

To avoid testing source tree I'm using some exact testing methodology using exact methodolowgy:
- "setup.py build"
- "setup.py install --root </install/prefix>"
- "pytest with PYTHONPATH pointing to setearch and sitelib inside </install/prefix>

Here are results of using pytest and tox that way.
pytest:
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-dateutil-2.8.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-dateutil-2.8.2-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.11, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2, configfile: setup.cfg
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, expect-1.1.0, httpbin-1.0.0, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, freezegun-0.4.2, case-1.5.3, isort-1.3.0, aspectlib-1.5.2, asyncio-0.15.1, toolbox-0.5, xprocess-0.17.1, aiohttp-0.3.0, checkdocs-2.7.0, mock-3.6.1, rerunfailures-9.1.1, requests-mock-1.9.3, cov-2.12.1, pyfakefs-4.5.0, flaky-3.7.0, hypothesis-6.14.0, benchmark-3.4.1, xdist-2.3.0, pylama-7.7.1, datadir-1.3.1, regressions-2.2.0, cases-3.6.3, Faker-8.10.0
collected 0 items / 1 error

================================================================================== ERRORS ==================================================================================
______________________________________________________________________ ERROR collecting test session _______________________________________________________________________
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:961: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:973: in _find_and_load_unlocked
    ???
E   ModuleNotFoundError: No module named 'dateutil.test'
========================================================================= short test summary info ==========================================================================
ERROR  - ModuleNotFoundError: No module named 'dateutil.test'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================= 1 error in 0.28s =============================================================================
```
In this case pytest is failing becauw etest suite is using provate `dateutil.test` which is not availabe over `sys.path`
And tox:
```console
+ /usr/bin/tox --skip-missing-interpreters
.package create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/.package
.package installdeps: setuptools; python_version != '3.3', setuptools<40.0; python_version == '3.3', wheel, setuptools_scm
py27 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/py27
SKIPPED: InterpreterNotFound: python2.7
py33 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/py33
SKIPPED: InterpreterNotFound: python3.3
py34 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/py34
SKIPPED: InterpreterNotFound: python3.4
py35 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/py35
SKIPPED: InterpreterNotFound: python3.5
py36 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/py36
SKIPPED: InterpreterNotFound: python3.6
py37 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/py37
SKIPPED: InterpreterNotFound: python3.7
pypy create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/pypy
SKIPPED: InterpreterNotFound: pypy
pypy3 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/pypy3
SKIPPED: InterpreterNotFound: pypy3
coverage create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/coverage
coverage installdeps: coverage
coverage installed: coverage==5.5
coverage run-test-pre: PYTHONHASHSEED='3866903251'
coverage run-test: commands[0] | python -m coverage erase
coverage run-test: commands[1] | python -m coverage combine
No data to combine
ERROR: InvocationError for command /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/coverage/bin/python -m coverage combine (exited with code 1)
docs create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/docs
SKIPPED: InterpreterNotFound: python3.6
_________________________________________________________________________________ summary __________________________________________________________________________________
SKIPPED:  py27: InterpreterNotFound: python2.7
SKIPPED:  py33: InterpreterNotFound: python3.3
SKIPPED:  py34: InterpreterNotFound: python3.4
SKIPPED:  py35: InterpreterNotFound: python3.5
SKIPPED:  py36: InterpreterNotFound: python3.6
SKIPPED:  py37: InterpreterNotFound: python3.7
SKIPPED:  pypy: InterpreterNotFound: pypy
SKIPPED:  pypy3: InterpreterNotFound: pypy3
ERROR:   coverage: commands failed
SKIPPED:  docs: InterpreterNotFound: python3.6
```
tox executed over `pythin -m tox is failing as well
```console
+ /usr/bin/python3 -m tox --skip-missing-interpreters
.package create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/.package
.package installdeps: setuptools; python_version != '3.3', setuptools<40.0; python_version == '3.3', wheel, setuptools_scm
py27 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/py27
SKIPPED: InterpreterNotFound: python2.7
py33 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/py33
SKIPPED: InterpreterNotFound: python3.3
py34 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/py34
SKIPPED: InterpreterNotFound: python3.4
py35 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/py35
SKIPPED: InterpreterNotFound: python3.5
py36 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/py36
SKIPPED: InterpreterNotFound: python3.6
py37 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/py37
SKIPPED: InterpreterNotFound: python3.7
pypy create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/pypy
SKIPPED: InterpreterNotFound: pypy
pypy3 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/pypy3
SKIPPED: InterpreterNotFound: pypy3
coverage create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/coverage
coverage installdeps: coverage
coverage installed: coverage==5.5
coverage run-test-pre: PYTHONHASHSEED='1291744242'
coverage run-test: commands[0] | python -m coverage erase
coverage run-test: commands[1] | python -m coverage combine
No data to combine
ERROR: InvocationError for command /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/coverage/bin/python -m coverage combine (exited with code 1)
docs create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/docs
SKIPPED: InterpreterNotFound: python3.6
_________________________________________________________________________________ summary __________________________________________________________________________________
SKIPPED:  py27: InterpreterNotFound: python2.7
SKIPPED:  py33: InterpreterNotFound: python3.3
SKIPPED:  py34: InterpreterNotFound: python3.4
SKIPPED:  py35: InterpreterNotFound: python3.5
SKIPPED:  py36: InterpreterNotFound: python3.6
SKIPPED:  py37: InterpreterNotFound: python3.7
SKIPPED:  pypy: InterpreterNotFound: pypy
SKIPPED:  pypy3: InterpreterNotFound: pypy3
ERROR:   coverage: commands failed
SKIPPED:  docs: InterpreterNotFound: python3.6
```
coverage and tox version:
```console
[tkloczko@barrel SPECS]$ pip show coverage| grep Version
Version: 5.6b1
[tkloczko@barrel SPECS]$ pip show tox| grep Version
Version: 3.14.6
```
I'm using python 3.8.11

**Comment by kloczek** [comment]
Just tested 2.8.1 and results are the same.

**Comment by mariocj89** [comment]
Thanks @kloczek, we should probably move this whole thing to the src layout. I'll try to take a stab at it before the end of the week, which should also force me to fix any other issue there.

**Comment by kloczek** [comment]
Pleasew let me know when you will have reorganized code.
I'll be glad to test those changes in my build env before actual next release.

Thank you :)

**Comment by mariocj89** [comment]
Thanks! I'm working on the changes on the following PR: https://github.com/dateutil/dateutil/pull/1146#discussion_r671359852

**Comment by kloczek** [comment]
tox and pytest are still failing.
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-dateutil-2.8.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-dateutil-2.8.2-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.11, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2, configfile: setup.cfg
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, expect-1.1.0, httpbin-1.0.0, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, freezegun-0.4.2, case-1.5.3, isort-1.3.0, aspectlib-1.5.2, asyncio-0.15.1, toolbox-0.5, xprocess-0.17.1, aiohttp-0.3.0, checkdocs-2.7.0, mock-3.6.1, rerunfailures-9.1.1, requests-mock-1.9.3, cov-2.12.1, pyfakefs-4.5.0, flaky-3.7.0, hypothesis-6.14.0, benchmark-3.4.1, xdist-2.3.0, pylama-7.7.1, datadir-1.3.1, regressions-2.2.0, cases-3.6.3, Faker-8.10.0
collected 0 items / 1 error

================================================================================== ERRORS ==================================================================================
______________________________________________________________________ ERROR collecting test session _______________________________________________________________________
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:961: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:973: in _find_and_load_unlocked
    ???
E   ModuleNotFoundError: No module named 'dateutil.test'
========================================================================= short test summary info ==========================================================================
ERROR  - ModuleNotFoundError: No module named 'dateutil.test'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================= 1 error in 0.38s =============================================================================
```
```console
+ /usr/bin/tox --skip-missing-interpreters
.package create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/.package
.package installdeps: setuptools; python_version != '3.3', setuptools<40.0; python_version == '3.3', wheel, setuptools_scm
py27 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/py27
SKIPPED: InterpreterNotFound: python2.7
py33 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/py33
SKIPPED: InterpreterNotFound: python3.3
py34 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/py34
SKIPPED: InterpreterNotFound: python3.4
py35 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/py35
SKIPPED: InterpreterNotFound: python3.5
py36 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/py36
SKIPPED: InterpreterNotFound: python3.6
py37 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/py37
SKIPPED: InterpreterNotFound: python3.7
pypy create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/pypy
SKIPPED: InterpreterNotFound: pypy
pypy3 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/pypy3
SKIPPED: InterpreterNotFound: pypy3
coverage create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/coverage
coverage installdeps: coverage
coverage installed: coverage==5.5
coverage run-test-pre: PYTHONHASHSEED='1083735381'
coverage run-test: commands[0] | python -m coverage erase
coverage run-test: commands[1] | python -m coverage combine
No data to combine
ERROR: InvocationError for command /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/coverage/bin/python -m coverage combine (exited with code 1)
docs create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/docs
SKIPPED: InterpreterNotFound: python3.6
_________________________________________________________________________________ summary __________________________________________________________________________________
SKIPPED:  py27: InterpreterNotFound: python2.7
SKIPPED:  py33: InterpreterNotFound: python3.3
SKIPPED:  py34: InterpreterNotFound: python3.4
SKIPPED:  py35: InterpreterNotFound: python3.5
SKIPPED:  py36: InterpreterNotFound: python3.6
SKIPPED:  py37: InterpreterNotFound: python3.7
SKIPPED:  pypy: InterpreterNotFound: pypy
SKIPPED:  pypy3: InterpreterNotFound: pypy3
ERROR:   coverage: commands failed
SKIPPED:  docs: InterpreterNotFound: python3.6
```
In case of pytest it fails because what is in `src/dateutil/test` is not part of the resources generated by setuptools `build` in build/lib/dateutil:
```console
[tkloczko@barrel dateutil-2.8.2]$ ls -l build/lib/dateutil
total 120
-rw-r--r-- 1 tkloczko tkloczko   932 Jul 19 09:55 _common.py
-rw-r--r-- 1 tkloczko tkloczko  2678 Jul 19 09:55 easter.py
-rw-r--r-- 1 tkloczko tkloczko   222 Jul 19 09:55 __init__.py
drwxr-xr-x 1 tkloczko tkloczko    66 Jul 19 09:55 parser
-rw-r--r-- 1 tkloczko tkloczko 24904 Jul 19 09:55 relativedelta.py
-rw-r--r-- 1 tkloczko tkloczko 66556 Jul 19 09:55 rrule.py
drwxr-xr-x 1 tkloczko tkloczko    90 Jul 19 09:55 tz
-rw-r--r-- 1 tkloczko tkloczko    59 Jul 19 09:55 tzwin.py
-rw-r--r-- 1 tkloczko tkloczko  1965 Jul 19 09:55 utils.py
-rw-r--r-- 1 tkloczko tkloczko   142 Jul 19 09:55 _version.py
drwxr-xr-x 1 tkloczko tkloczko    42 Jul 19 09:55 zoneinfo
```

**Comment by mariocj89** [comment]
Thanks @kloczek, I just updated https://github.com/dateutil/dateutil/pull/1146, do you still see issues with that version? Things should work fine now.

**Comment by kloczek** [comment]
Just tested that PR and still tox and pytest are not working
tox:
```console
+ /usr/bin/tox --skip-missing-interpreters
.package create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/.package
.package installdeps: setuptools; python_version != '3.3', setuptools<40.0; python_version == '3.3', wheel, setuptools_scm
py27 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/py27
SKIPPED: InterpreterNotFound: python2.7
py33 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/py33
SKIPPED: InterpreterNotFound: python3.3
py34 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/py34
SKIPPED: InterpreterNotFound: python3.4
py35 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/py35
SKIPPED: InterpreterNotFound: python3.5
py36 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/py36
SKIPPED: InterpreterNotFound: python3.6
py37 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/py37
SKIPPED: InterpreterNotFound: python3.7
pypy create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/pypy
SKIPPED: InterpreterNotFound: pypy
pypy3 create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/pypy3
SKIPPED: InterpreterNotFound: pypy3
coverage create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/coverage
coverage installdeps: coverage
coverage installed: coverage==5.5
coverage run-test-pre: PYTHONHASHSEED='3039697023'
coverage run-test: commands[0] | python -m coverage erase
coverage run-test: commands[1] | python -m coverage combine
No data to combine
ERROR: InvocationError for command /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/coverage/bin/python -m coverage combine (exited with code 1)
docs create: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/.tox/docs
SKIPPED: InterpreterNotFound: python3.6
_________________________________________________________________________________ summary __________________________________________________________________________________
SKIPPED:  py27: InterpreterNotFound: python2.7
SKIPPED:  py33: InterpreterNotFound: python3.3
SKIPPED:  py34: InterpreterNotFound: python3.4
SKIPPED:  py35: InterpreterNotFound: python3.5
SKIPPED:  py36: InterpreterNotFound: python3.6
SKIPPED:  py37: InterpreterNotFound: python3.7
SKIPPED:  pypy: InterpreterNotFound: pypy
SKIPPED:  pypy3: InterpreterNotFound: pypy3
ERROR:   coverage: commands failed
SKIPPED:  docs: InterpreterNotFound: python3.6
```
pytest
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-dateutil-2.8.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-dateutil-2.8.2-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
Using --randomly-seed=2420231914
rootdir: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2, configfile: setup.cfg
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, expect-1.1.0, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, freezegun-0.4.2, aspectlib-1.5.2, toolbox-0.5, rerunfailures-9.1.1, requests-mock-1.9.3, cov-2.12.1, flaky-3.7.0, benchmark-3.4.1, xdist-2.3.0, pylama-7.7.1, datadir-1.3.1, regressions-2.2.0, cases-3.6.3, xprocess-0.18.1, black-0.3.12, anyio-3.3.0, asyncio-0.15.1, trio-0.7.0, subtests-0.5.0, isort-2.0.0, hypothesis-6.14.6, mock-3.6.1, profiling-1.7.0, randomly-3.8.0, Faker-8.12.1, nose2pytest-1.0.8, pyfakefs-4.5.1, tornado-0.8.1, twisted-1.13.3
collected 0 items / 1 error

================================================================================== ERRORS ==================================================================================
______________________________________________________________________ ERROR collecting test session _______________________________________________________________________
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:961: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:973: in _find_and_load_unlocked
    ???
E   ModuleNotFoundError: No module named 'dateutil.test'
========================================================================= short test summary info ==========================================================================
ERROR  - ModuleNotFoundError: No module named 'dateutil.test'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================= 1 error in 0.39s =============================================================================
pytest-xprocess reminder::Be sure to terminate the started process by running 'pytest --xkill' if you have not explicitly done so in your fixture with 'xprocess.getinfo(<process_name>).terminate()'.
```

**Comment by kloczek** [comment]
Update.
With latest pytest I have new output:
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-dateutil-2.8.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-dateutil-2.8.2-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2, configfile: setup.cfg
plugins: hypothesis-6.34.2
collected 2085 items
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 322, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 333, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 637, in perform_collect
INTERNALERROR>     hook.pytest_collection_modifyitems(
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/tkloczko/rpmbuild/BUILD/dateutil-2.8.2/src/dateutil/test/conftest.py", line 20, in pytest_collection_modifyitems
INTERNALERROR>     item.add_marker(pytest.mark.no_cover)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/mark/structures.py", line 510, in __getattr__
INTERNALERROR>     warnings.warn(
INTERNALERROR> pytest.PytestUnknownMarkWarning: Unknown pytest.mark.no_cover - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html

========================================================================== no tests ran in 1.71s ===========================================================================
```

**Comment by kloczek** [comment]
Gentle ping .. any update? 🤔
