### ISSUE TITLE
fuzzy_with_tokens confused over date-like words

### ISSUE THREAD

**Issue by timcoote** [dateutil/dateutil#1188]
Here's a simple example of what I mean:
```
>>> from dateutil.parser import parse
>>> parse ("1 Jan 1999 (but I could be late)", fuzzy_with_tokens=True)
(datetime.datetime(1999, 1, 1, 0, 0), (' ', '(but I could be late)'))
>>> parse ("1 Jan 1999 (but I may be late)", fuzzy_with_tokens=True)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/tim/Projects/telemarq/c19capture/venv/lib/python3.9/site-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/Users/tim/Projects/telemarq/c19capture/venv/lib/python3.9/site-packages/dateutil/parser/_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: 1 Jan 1999 (but I may be late)
```

The first example gets parsed, the second does not. It looks like the `may` is confusing the parser. It's also possible to break it with other date related words (I tried 'Jan' as a legitimate person's name).  It's a particularly messy issue if the date happens to have the same month as the noise word.

Version info:
Python 3.9.9 (main, Nov 21 2021, 03:23:44) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin

>>> dateutil.__version__
'2.8.2'

**Comment by jbrockmendel** [comment]
Could add an xfailed test for this (grep for TestParseUnimplementedCases).  But really, I think its unlikely this case is going to be supported within dateutil.

**Comment by timcoote** [comment]
@jbrockmendel are you asking that I produce a test? I'm happy to do that, but I'd need better instructions, I'm afraid.

It makes sense that dateutil doesn't try to capture these situations, but I think that the users should be told.
