### ISSUE TITLE
2.8.2: why `dateutil` is using own zoneinfo files?🤔 

### ISSUE THREAD

**Issue by kloczek** [dateutil/dateutil#1217]
I was a bit surprised when I found on testing latest `hypothesis` module when I found that in `hypothesis` test suite few units are failing because they've not been able to locate dateutil-zoneinfo.tar.gz file.
From `hypothesis` test suite output:
<details>

```console
_____________________________________________________________________ test_can_generate_non_naive_time _____________________________________________________________________
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/dateutil/zoneinfo/__init__.py", line 24, in getzoneinfofile_stream
    return BytesIO(get_data(__name__, ZONEFILENAME))
  File "/usr/lib64/python3.8/pkgutil.py", line 638, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap_external>", line 1032, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.8/site-packages/dateutil/zoneinfo/dateutil-zoneinfo.tar.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.46.8/hypothesis-python/tests/datetime/test_dateutil_timezones.py", line 31, in test_can_generate_non_naive_time
    assert minimal(times(timezones=timezones()), lambda d: d.tzinfo).tzinfo == tz.UTC
  File "/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-6.46.8/hypothesis-python/tests/common/debug.py", line 64, in minimal
    definition.validate()
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-hypothesis-6.46.8-2.fc35.x86_64/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/strategies.py", line 407, in validate
    self.do_validate()
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-hypothesis-6.46.8-2.fc35.x86_64/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/lazy.py", line 129, in do_validate
    w = self.wrapped_strategy
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-hypothesis-6.46.8-2.fc35.x86_64/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/lazy.py", line 104, in wrapped_strategy
    unwrapped_kwargs = {
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-hypothesis-6.46.8-2.fc35.x86_64/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/lazy.py", line 105, in <dictcomp>
    k: unwrap_strategies(v) for k, v in self.__kwargs.items()
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-hypothesis-6.46.8-2.fc35.x86_64/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/lazy.py", line 42, in unwrap_strategies
    result = unwrap_strategies(s.wrapped_strategy)
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-hypothesis-6.46.8-2.fc35.x86_64/usr/lib/python3.8/site-packages/hypothesis/strategies/_internal/lazy.py", line 108, in wrapped_strategy
    base = self.function(*self.__args, **self.__kwargs)
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-hypothesis-6.46.8-2.fc35.x86_64/usr/lib/python3.8/site-packages/hypothesis/extra/dateutil.py", line 56, in timezones
    (tz.gettz(t) for t in zoneinfo.get_zonefile_instance().zones),
  File "/usr/lib/python3.8/site-packages/dateutil/zoneinfo/__init__.py", line 102, in get_zonefile_instance
    zif = ZoneInfoFile(getzoneinfofile_stream())
  File "/usr/lib/python3.8/site-packages/dateutil/zoneinfo/__init__.py", line 26, in getzoneinfofile_stream
    warnings.warn("I/O error({0}): {1}".format(e.errno, e.strerror))
UserWarning: I/O error(2): No such file or directory
```
</details>

That was kind of accidental discovery because I'm using as source tar ball tar autogenerated by github from git tag and looks like you are relaying on data files identification provided by `setuptools-scm` module (instead listing that kind of files in MANIFEST.in).
IMO `dateutils` should use system zoneinfo database.
Personally I would even prefer to patch `dateutils` to use only system zoneinfo data files instead fall back to that tar in case of not finding system zoneinfo data files.

Do you have maybe somewhere version of the `dateutil/zoneinfo/__init__.py` which is using only system zoneinfo?

**Comment by pganssle** [comment]
Because #1130 is not done and shipped. This only applies when a zone cannot be found in the normal search path (e.g. on Windows).

**Comment by kloczek** [comment]
> Because #1130 is not done and shipped. This only applies when a zone cannot be found in the normal search path (e.g. on Windows).

It affects as well build on Linux.

**Comment by dvzrv** [comment]
Building latest hypothesis (6.98.17) for the package on Arch Linux I also ran into failing tests due to the file missing.

If the file is expected by consumers it would be great if its removal could be documented accordingly as this seems to be a breaking change.

**Comment by pganssle** [comment]
I am confused as to what is being reported. The question in the title says "Why is `dateutil` using its own `zoneinfo` files". The answer is "because we haven't shipped the thing that removes it yet"

The body of the text mentions doing some sort of build from a git tag, I guess? I am not sure, but the supported way to build `dateutil` is from the files released to PyPI, and those contain the relevant tarball:

```
$ pip download python-dateutil
...
$ unzip python_dateutil-2.9.0.post0.dist-info
...
$ ls dateutil/zoneinfo/
dateutil-zoneinfo.tar.gz  __init__.py  rebuild.py
```

Nothing has been removed. If you are trying to build `python-dateutil` some other way, that's fine, but changes that break your ad hoc workflows are not considered breaking changes to this project and may not be documented if they do not rely on the public interface.
