### ISSUE TITLE
Python3.12: DeprecationWarning: datetime.utcfromtimestamp() is deprecated

### ISSUE THREAD

**Issue by garyvdm** [dateutil/dateutil#1339]
When importing `dateutil.tz` with python3.12, the following warning happens:

```
>>> import dateutil.tz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gary/dev/bpm-ng/python/ve/lib64/python3.12/site-packages/dateutil/tz/__init__.py", line 2, in <module>
    from .tz import *
  File "/home/gary/dev/bpm-ng/python/ve/lib64/python3.12/site-packages/dateutil/tz/tz.py", line 37, in <module>
    EPOCH = datetime.datetime.utcfromtimestamp(0)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
```

**Comment by alvarosantossyngenta** [comment]
Hi. I found that you fix this issue in a commit some time ago. However, there is not any new release for it. When is it planned to do it?
