### ISSUE TITLE
decimal.InvalidOperation exception

### ISSUE THREAD

**Issue by senier** [dateutil/dateutil#1366]
Hi,

during some experiments with my [fuzzer](https://github.com/senier/cobrafuzz), I found a parser input which causes an `InvalidOpersion` exception in dateutil. In case you want to look into it, here is a reproducer. Find the Python and dateutil versions below.

```sh
$ python -c "import dateutil.parser; dateutil.parser.parse('19970902090807197090209080710h')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/venv/lib/python3.11/site-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.11/site-packages/dateutil/parser/_parser.py", line 640, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.11/site-packages/dateutil/parser/_parser.py", line 740, in _parse
    i = self._parse_numeric_token(l, i, info, ymd, res, fuzzy)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.11/site-packages/dateutil/parser/_parser.py", line 936, in _parse_numeric_token
    self._assign_hms(res, value_repr, hms)
  File "/tmp/venv/lib/python3.11/site-packages/dateutil/parser/_parser.py", line 1047, in _assign_hms
    if value % 1:
       ~~~~~~^~~
decimal.InvalidOperation: [<class 'decimal.DivisionImpossible'>]
```

```sh
$ python --version
Python 3.11.2
```

```sh
$ python -c "import dateutil; print(dateutil.__version__)"
2.9.0.post0
```

**Comment by minrk** [comment]
Another reproducer for failing to parse valid dates when decimal module precision is set:

```python
import decimal
from dateutil.parser import parse as parse_date

ts = "2024-08-08T09:17:24Z"
parse_date(ts)  # ok
con = decimal.getcontext()
con.prec = 1
parse_date(ts)  # error
```
