### ISSUE TITLE
`pip download` command fails due to breaking change in setuptools

### ISSUE THREAD

**Issue by safiyat** [dateutil/dateutil#1379]
## Summary
As of 29th July 2024, setuptools released a [new version 72.0.0](https://github.com/pypa/setuptools/releases/tag/v72.0.0) which adds [breaking change](https://setuptools.pypa.io/en/stable/history.html#v72-0-0).

This causes the following error when running `python -m pip download python-dateutil`.

```
$ python -m pip download --dest /tmp --no-binary :all: python-dateutil
Collecting python-dateutil
  Downloading python-dateutil-2.9.0.post0.tar.gz (342 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File ".../venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File ".../venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File ".../venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/jw/tdz0ld7s2wzc1m8mcdy8p_0h0000gn/T/pip-build-env-7kl4rlkx/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/private/var/folders/jw/tdz0ld7s2wzc1m8mcdy8p_0h0000gn/T/pip-build-env-7kl4rlkx/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/jw/tdz0ld7s2wzc1m8mcdy8p_0h0000gn/T/pip-build-env-7kl4rlkx/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 7, in <module>
      ModuleNotFoundError: No module named 'setuptools.command.test'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### Environment
pip: 24.2
python: 3.8.19
setuptools: 72.0.0

**Comment by chenrui333** [comment]
@safiyat I think this might have been fixed, I cannot reproduce anymore with setuptools-72.1.0

```
$ python -m pip install --verbose --no-deps --no-binary=:all: --ignore-installed --no-compile python-dateutil
Using pip 24.0 from /Users/rui/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pip (python 3.12)
Collecting python-dateutil
  Using cached python-dateutil-2.9.0.post0.tar.gz (342 kB)
  Running command pip subprocess to install build dependencies
  Ignoring setuptools: markers 'python_version == "3.3"' don't match your environment
  Collecting setuptools
    Using cached setuptools-72.1.0-py3-none-any.whl
  Collecting wheel
    Using cached wheel-0.43.0-py3-none-any.whl
  Collecting setuptools_scm<8.0
    Using cached setuptools_scm-7.1.0-py3-none-any.whl
  Collecting packaging>=20.0 (from setuptools_scm<8.0)
    Using cached packaging-24.1-py3-none-any.whl
  Collecting typing-extensions (from setuptools_scm<8.0)
    Using cached typing_extensions-4.12.2-py3-none-any.whl
  Installing collected packages: wheel, typing-extensions, setuptools, packaging, setuptools_scm
  Successfully installed packaging-24.1 setuptools-72.1.0 setuptools_scm-7.1.0 typing-extensions-4.12.2 wheel-0.43.0
  ...
Successfully built python-dateutil
Installing collected packages: python-dateutil
Successfully installed python-dateutil-2.9.0.post0
```

**Comment by safiyat** [comment]
Yes, the code change was [reversed](https://github.com/pypa/setuptools/commit/c437aaa8d5b969a9fe8c8147463bfcb85b31ab26) and the release 72.0.0 of setuptools was [yanked](https://pypi.org/project/setuptools/72.0.0/).

This reversal will be reversed, i.e., the tests module will be removed (again) in the future. I read somewhere that it will be in November 2024, but I can't find a link to any such announcement.

**Comment by hugovk** [comment]
> Yes, the code change was [reversed](https://github.com/pypa/setuptools/commit/c437aaa8d5b969a9fe8c8147463bfcb85b31ab26) ... I read somewhere that it will be in November 2024, but I can't find a link to any such announcement.

15th November 2024: you can see `due_date=(2024, 11, 15)` in the warning in the linked commit.
