### ISSUE TITLE
tzwin does not accept some values returned by tzname

### ISSUE THREAD

**Issue by labrys** [dateutil/dateutil#144]
Some values returned by `tzname` are not valid for `tzwin`.  It appears `tzwin` doesn't like daylight savings time names even though `tzname` returns them.
```python
import datetime
import dateutil.tz

now = datetime.datetime.now()

tzwl_name = dateutil.tz.tzwinlocal().tzname(now)
print tzwl_name  # 'Eastern Daylight Time'

tzw_name = dateutil.tz.tzwin('Eastern Standard Time').tzname(now)
print tzw_name  # 'Eastern Daylight Time'

gettz_name = dateutil.tz.gettz(tzwl_name).tzname(now)
print gettz_name  # 'Eastern Standard Time'

dateutil.tz.tzwin(tzwl_name)  # raises WindowsError
```
```
Eastern Daylight Time
Eastern Daylight Time
Eastern Standard Time
Traceback (most recent call last):
  File "C:/python/date.cur/test.py", line 30, in <module>
    dateutil.tz.tzwin(name)
  File "C:\python\date.cur\dateutil\tz\win.py", line 92, in __init__
    "%s\%s" % (TZKEYNAME, name)) as tzkey:
WindowsError: [Error 2] The system cannot find the file specified
```
`tzname`s are inconsistent, however that appears to be a separate issue (see #143)

**Comment by pganssle** [comment]
I'm not sure if this is a real problem or not. I think the fact that `tzname` requires a datetime argument indicates that it is supposed to be the localized time zone name (e.g. including DST). It seems like Windows does not allow lookup by the DST name.

Is this something that actually comes up? If it's an actual problem, then maybe we can consider exposing `tzwin._stdname` and `tzwin._dstname` as properties, because Windows will want to look up the time zone by `tzwin._stdname`.

**Comment by labrys** [comment]
This is more one of those principle of least surprise things.  

When I first started testing the library, one of the first things I tried was `tzwin('Eastern Daylight Time')` since it was daylight savings time.  I got the above error.  I figured no problem, it doesn't expect 'Eastern Daylight Time' as a valid timezone.  So I tried variants like 'US Eastern Daylight Time', and 'EDT' and all lowercase since it was quicker than looking up the docs.  

Those failed so, of course the next thing I tried was `tzwinlocal().tzname(datetime.datetime.now())` to find a valid `tzname()` and was suprised to see it then respond with `Eastern Daylight Time`.  

It would be natural to assume that any name returned should be able to be used as an argument.  In addition, while I have yet to do any tests with pickling dateutil objects, I was wondering if this would present any issues there.

**Comment by pganssle** [comment]
I think this may be an issue with Windows and not with dateutil. Consider the results on Linux:

```python
import datetime
from dateutil import tz
>>> tz.tzlocal().tzname(datetime.datetime(2015, 8, 5))
'EDT'

>>> tz.tzlocal().tzname(datetime.datetime(2015, 12, 5))
'EST'
```

And Windows:
```python
>>> tz.tzwinlocal().tzname(datetime.datetime(2015, 8, 5))
'Eastern Daylight Time'

>>> tz.tzwinlocal().tzname(datetime.datetime(2015, 12, 5))
'Eastern Standard Time'
```

Seems consistent. The problem is that Windows apparently doesn't have a registry key for either the DST or display variants of the names, so the lookup is one-way. Unless there's another lookup table I'm not aware of, we'd have to build our own lookup table by iterating through the time zones, looking up their information, then pulling out the DST-variant of the name, if it exists, and using that as a key to the standard representation.

I'll keep this issue open for now to invite discussion on whether 1. it's worth building such a lookup table (preferably lazily, in a cached way) or 2. if there's a better way to look up time zones on Windows.

**Comment by pganssle** [comment]
This doesn't seem to be as critical as the other tzwin-related errors, so I'm pushing it to 2.5.1.
