### ISSUE TITLE
tz submodule not created by setup.py install

### ISSUE THREAD

**Issue by bjamesv** [dateutil/dateutil#165]
setup.py install appears to skip the dateutil.tz submodule:
```bash
$ pip install git+https://github.com/dateutil/dateutil.git@5dd5c9a#egg=python-dateutil
Collecting python-dateutil from git+https://github.com/dateutil/dateutil.git@5dd5c9a#egg=python-dateutil
  Cloning https://github.com/dateutil/dateutil.git (to 5dd5c9a) to /tmp/pip-build-0g7nur3q/python-dateutil
p11-kit: invalid config filename, will be ignored in the future: /etc/pkcs11/modules/gnome-keyring-module
  Could not find a tag or branch '5dd5c9a', assuming commit.
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in ./build/miniconda3/envs/warehouse-env/lib/python3.4/site-packages (from python-dateutil)
Installing collected packages: python-dateutil
  Running setup.py install for python-dateutil
Successfully installed python-dateutil-2.4.2
$ echo "import dateutil.parser"|python3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bjv/git/warehouse/server/build/miniconda3/envs/warehouse-env/lib/python3.4/site-packages/dateutil/parser.py", line 57, in <module>
    from . import tz
ImportError: cannot import name 'tz'
```

**Comment by pganssle** [comment]
Fixed in #166.
