### ISSUE TITLE
Spaces are not treaded well

### ISSUE THREAD

**Issue by Allactaga** [dateutil/dateutil#19]
Is it expected behavior?
```python
>>> from dateutil import parser
>>> parser.parse("Jan.5.2014")
datetime.datetime(2014, 1, 5, 0, 0)
>>> parser.parse("Jan. 5.2014")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/allactaga/Development/Environments/scrapinghub.sprinklr/lib/python2.7/site-packages/dateutil/parser.py", line 743, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/Users/allactaga/Development/Environments/scrapinghub.sprinklr/lib/python2.7/site-packages/dateutil/parser.py", line 303, in parse
    raise ValueError("unknown string format")
ValueError: unknown string format
```

**Comment by pganssle** [comment]
Looking into this a bit, this is definitely not the expected behavior, as you don't get the same problem if you have `"Jan.05.2014"` vs., `"Jan. 05.2014"`. I'll try and figure out why this is happening.

**Comment by pganssle** [comment]
OK, I've looked into this some more, and it's actually a bit complicated to fix, because doing it right may involve fairly dramatic changes to the way these things are parsed. The crux of the issue is that dots are both a valid separator (`Jan.5.2014` or `01.05.2014`) and the delimiter for decimal fractions (`12:;36:21.44`).

One problem is that it's not possible to distinguish between interpreting `'Jan. 5.2014'` as "January 5, 2014" and "4:50 AM on January 5" (e.g. January 5th + 0.2014 days). Neither format seems particularly likely to be prevalent.

**Comment by Someshwar-prox** [comment]
Hey, I found a fix for this. The issue is in the tokenizer — when there's a space after a month abbreviation dot (like `Jan. 5.2014`), it produces `5.2014` as a single numeric token, which the parser can't handle in the YYMMDD/HHMMSS branch.

I've opened PR #1528 that handles this by detecting `day.year` format in numeric tokens and splitting them into separate components. All 231 existing tests pass.

PR: https://github.com/dateutil/dateutil/pull/1528
