### ISSUE TITLE
utcoffset crash on Windows with EPOCH  and tzlocal for timezone GMT+x

### ISSUE THREAD

**Issue by ggtools** [dateutil/dateutil#197]
My local time zone is Europe/Paris and I noticed that on Windows the following operation crashed:

    >>> datetime.fromtimestamp(0,tz.tzlocal())
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Anaconda3\lib\site-packages\dateutil\tz.py", line 99, in utcoffset
        if self._isdst(dt):
      File "C:\Anaconda3\lib\site-packages\dateutil\tz.py", line 143, in _isdst
        return time.localtime(timestamp+time.timezone).tm_isdst
    OSError: [Errno 22] Invalid argument

The same on Linux is working fine.

Looking at the code I discovered that the issue is caused by the call to `time.localtime()` with `-3600` as argument. This is working fine on Linux but not on Windows.

**Comment by ggtools** [comment]
There's a workaround which is to use: `datetime.fromtimestamp(0).replace(tzinfo=tz.tzlocal())` instead of `datetime.fromtimestamp(0,tz.tzlocal())`

**Comment by labrys** [comment]
@ggtools which version of dateutil as I can't duplicate with 2.5.0?  I assume prior to 2.5.0 as there were several issues with Windows that @pganssle has fixed.  Does this also fail with `tzwinlocal()`?

**Comment by ggtools** [comment]
I'm using dateutils 2.5.0:

```[Anaconda3] C:\Users\xtof>pip install --upgrade python-dateutil
Collecting python-dateutil
  Downloading python_dateutil-2.5.0-py2.py3-none-any.whl (199kB)
    100% |################################| 200kB 910kB/s
Requirement already up-to-date: six>=1.5 in c:\anaconda3\lib\site-packages (from python-dateutil)
Installing collected packages: python-dateutil
  Found existing installation: python-dateutil 2.4.2
    Uninstalling python-dateutil-2.4.2:
      Successfully uninstalled python-dateutil-2.4.2
Successfully installed python-dateutil-2.5.0
```
However this'll only happen if you local time zone is currently in GMT+x like Europe/Paris which is in GMT+1 at the moment. On my box the value of `time.timezone` is `-3600`.

Using `tzwinlocal()` fixes the issue.

**Comment by labrys** [comment]
@ggtools After changing to UTC+1 and restarting idle, I was able to reproduce this (it apparently didn't register the change in timezone the first time).  However I get oddly different results from Python 2.7.11 and Python 3.5.1.  In 2.7.11 `tz.tzlocal()` gives me a `ValueError` where 3.5.1 gives an `OSError`.  In 2.7.11 `tz.tzwinlocal()` gives me a valid result where 3.5.1. gives me a `ValueError`.  All tests run on Windows 10x64 with 32-bit python. See below:

```python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> from dateutil import tz
>>> from datetime import datetime
>>> datetime.fromtimestamp(0,tz.tzlocal())

Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    datetime.fromtimestamp(0,tz.tzlocal())
  File "C:\Python27\lib\site-packages\dateutil\tz\tz.py", line 99, in utcoffset
    if self._isdst(dt):
  File "C:\Python27\lib\site-packages\dateutil\tz\tz.py", line 143, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')
>>> datetime.fromtimestamp(0,tz.tzwinlocal())
datetime.datetime(1970, 1, 1, 1, 0, tzinfo=tzwinlocal())
>>> datetime.fromtimestamp(0).replace(tzinfo=tz.tzlocal())
datetime.datetime(1970, 1, 1, 1, 0, tzinfo=tzlocal())
>>> datetime.fromtimestamp(0).replace(tzinfo=tz.tzwinlocal())
datetime.datetime(1970, 1, 1, 1, 0, tzinfo=tzwinlocal())
>>> 
```

```python
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> from datetime import datetime
>>> from dateutil import tz
>>> datetime.fromtimestamp(0,tz.tzlocal())
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    datetime.fromtimestamp(0,tz.tzlocal())
  File "C:\Python35\lib\site-packages\dateutil\tz.py", line 113, in utcoffset
    if self._isdst(dt):
  File "C:\Python35\lib\site-packages\dateutil\tz.py", line 157, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
OSError: [Errno 22] Invalid argument
>>> datetime.fromtimestamp(0,tz.tzwinlocal())
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    datetime.fromtimestamp(0,tz.tzwinlocal())
ValueError: offset must be a timedelta strictly between -timedelta(hours=24) and timedelta(hours=24).
>>> datetime.fromtimestamp(0).replace(tzinfo=tz.tzlocal())
datetime.datetime(1970, 1, 1, 1, 0, tzinfo=tzlocal())
>>> datetime.fromtimestamp(0).replace(tzinfo=tz.tzwinlocal())
datetime.datetime(1970, 1, 1, 1, 0, tzinfo=<dateutil.tzwin.tzwinlocal object at 0x0100CDB0>)
>>> 
```

**Comment by ggtools** [comment]
Interesting. I'm using a fresh install of Anaconda 64 bit:

```python
Python 3.5.1 |Anaconda 2.5.0 (64-bit)| (default, Jan 29 2016, 15:01:46) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from datetime import datetime
>>> from dateutil import tz
>>> datetime.fromtimestamp(0,tz.tzwinlocal())
datetime.datetime(1970, 1, 1, 1, 0, tzinfo=tzwinlocal())
>>>
```

**Comment by labrys** [comment]
@ggtools maybe time of day?  If i change my timezone it thinks it's 16:35 here.  Try changing your time see if it fails.

**Comment by labrys** [comment]
@ggtools @pganssle It appears to be an issue with 32-bit python. As I get correct results on x64.

```python
>>> datetime.fromtimestamp(0,tz.tzwinlocal())
datetime.datetime(1970, 1, 1, 1, 0, tzinfo=tzwinlocal())
```

**Comment by pganssle** [comment]
Not sure if this helps, but I wrote a timezone-changing context manager for the Windows tests:

https://github.com/dateutil/dateutil/blob/master/dateutil/test/test_tz.py#L130

I can try and spin up a Windows VM and help figure this out at some point. Given that it's so finicky and implementation-dependent, I can't help but wonder if this might be a bug in Python itself.

**Comment by pganssle** [comment]
@labrys Very odd that the `repr` is wrong on 32-bit Python. Are you 100% sure that you are using dateutil 2.5.0 in the 32-bit version?

**Comment by ggtools** [comment]
@labrys @pganssle I guess it's more subtle since I download the *Windows x86 embeddable zip file* I extracted the zip file, and copied the *six.py* file and *dateutil* directory from my Anaconda installation. I removed all `__pycache__` directory I could find and it works:

```python
[...]\Downloads\python-3.5.1-embed-win32>python
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from dateutil import tz
>>> from datetime import datetime
>>> datetime.fromtimestamp(0, tz.tzwinlocal())
datetime.datetime(1970, 1, 1, 1, 0, tzinfo=tzwinlocal())
>>>
```

**Comment by labrys** [comment]
@pganssle I'll double check but as i just recently installed it for 3.5 (I was only running dateutil on 2.7.11 previously) it should be correct.

**Comment by labrys** [comment]
@pganssle apparently you were right I was still on 2.4.2 on 3.5.1x86.  The 2.7.11 was definitely 2.5.0 though.

**Comment by pganssle** [comment]
@labrys Yeah, we do have a test on x32 for the `repr`, so I would be surprised if that wasn't working. I've been trying to get it so tox works properly on my local machine and as a result I've completely messed up my $PATH, so I can never tell what version of python is associated with what version of pip. I figured something like that might have happened with the fresh install that was generating the wrong `repr`.

**Comment by labrys** [comment]
I don't have any in my path so I have to call them explicitly.. i just forgot that I had installed dateutil on 3.5 x86 recently to test your upcoming fixes, and never got around to updating it XD

**Comment by labrys** [comment]
@ggtools @pganssle since updating to dateutil 2.5.0 in sickrage, windows users are getting this (possibly related) timezone error.  It seems to be a unicode related bug as its causing:
```python
  File "C:\SickRage\SickRage\lib\dateutil\tz\win.py", line 239, in __init__
    handle, "%s\%s" % (TZKEYNAME, self._stdname)) as tzkey:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 57: ordinal not in range(128)"
```
The limited tests we've tried so far do not cause this error with `tz.tzlocal()`.  Changing timezones to e.g EST or to some other european timezones do not cause the error with `tz.tzwinlocal()`.
This was confirmed using python 2.7.10 (portable) on Server 2012 R2 and Windows 7 ultimate.

**Comment by labrys** [comment]
If you want I can make a new issue for this since it's not exactly the same thing, as this is a `tzwinlocal` issue and not `tzlocal`

**Comment by pganssle** [comment]
@labrys I think the issue is unrelated, so it should definitely be its own issue. I'm guessing it works fine on Python 3, which uses unicode literals.

**Comment by MinchinWeb** [comment]
I appear to be getting the exact same error. Windows 10 x64, Python 3.6.3 (x64), `dateutil` 2.6.1, current time is 9:14am using Mountain Standard Time (-7 offset from UTC):

![image](https://user-images.githubusercontent.com/1548809/34116281-61be17bc-e3d5-11e7-827f-83bfeaf5137d.png)

**Comment by IlyaOrson** [comment]
This [work around](https://stackoverflow.com/a/49139170/6313433) was useful for me:
```python
import os, time
from dateutil import tz
if os.name == 'nt':
    def _naive_is_dst(self, dt):
        timestamp = tz.tz._datetime_to_timestamp(dt)
        # workaround the bug of negative offset UTC prob
        if timestamp+time.timezone < 0:
            current_time = timestamp + time.timezone + 31536000
        else:
            current_time = timestamp + time.timezone
        return time.localtime(current_time).tm_isdst
tz.tzlocal._naive_is_dst = _naive_is_dst
```

**Comment by pganssle** [comment]
I think this may be: https://bugs.python.org/issue29097

**Comment by h-vetinari** [comment]
Update for this:

@pganssle 
That bug was fixed in 3.6.7 / 3.7.1, but the issue here still persists even with the fix

@IlyaOrson's workaround does the job for me, but the underlying issue remains - as noted by @ggtools  in the OP - that `time.localtime()` cannot deal with negative values on windows. Couldn't find a corresponding bug in the CPython bugtracker.
```
>>> time.localtime(-3600)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 22] Invalid argument
```

I'll also note that the original problem goes away with `tzwinlocal` instead of `tzlocal`:
```
>>> from datetime import datetime
>>> from dateutil import tz
>>> datetime.fromtimestamp(0, tz.tzlocal())
Traceback (most recent call last):
[...]
OSError: [Errno 22] Invalid argument
>>> datetime.fromtimestamp(0, tz.tzwinlocal())
datetime.datetime(1970, 1, 1, 1, 0, tzinfo=tzwinlocal())
```

Besides the point that I don't understand why there is a separate `tzwinlocal` at all - why not just point `tzlocal` to `tzwinlocal` (however it is implemented) behind the scenes when `os.name == 'nt'`?

**Comment by pganssle** [comment]
> Besides the point that I don't understand why there is a separate tzwinlocal at all - why not just point tzlocal to tzwinlocal (however it is implemented) behind the scenes when os.name == 'nt'?

There are several reasons for this. One is backwards compatibility (it would be a breaking change), but the more important one is that `tzlocal` and `tzwinlocal` do two different things. The latter actually reads data from the Windows registry and constructs a time zone object from it, the former is a simple wrapper around Python's `time` module's calls to the system time.

There are times when you explicitly want a `tzlocal` or a `tzwinlocal`, though they are probably rarer for the average person than they are for me (since I am often trying to test or demonstrate the properties of one or the other).

I think my preferred solution to the very real UX challenge you have identified, @h-vetinari, is to make `tz.gettz()` return `tz.tzwinlocal` instead of `tz.tzlocal`. In general, I think that `tz.gettz` is intended to get you the "right time zone object" for the job, and it may make sense to make `tz.tzwinlocal` the default "local time" on platforms where it's available. I've created issue #848 for discussion on the matter.

**Comment by pganssle** [comment]
> That bug was fixed in 3.6.7 / 3.7.1, but the issue here still persists even with the fix

> @IlyaOrson's workaround does the job for me, but the underlying issue remains - as noted by @ggtools in the OP - that time.localtime() cannot deal with negative values on windows. Couldn't find a corresponding bug in the CPython bugtracker.

Hm. I do not think this issue can be solved at the `dateutil` level. @IlyaOrson's workaround just shifts over the time by some fixed amount - I don't think it will work correctly for dates sufficiently far back in the past (though far enough back and the meaning of the time zone becomes a lot blurrier), and it may only give the "right answer" because Windows itself doesn't have sufficient support for the complexities of time zone handling in the past. If Windows ever fixes this and is able to support setting your local time to an IANA time zone with full historical information, Ilya's patch would lead to inaccuracies in the results.

I think the next step here is to raise a bug on CPython's issue tracker. If someone other than me makes the bug report (and given that I don't currently have a Windows machine it might be better for someone else to do it), please add me to the nosy list. My handle on there is p-ganssle.

**Comment by dagwieers** [comment]
This issue combined with https://github.com/dateutil/dateutil/issues/197 makes it impossible to get a local timezone on Windows reliably :-(

**Comment by groboclown** [comment]
I'm seeing this issue still happen using dateutil v2.8.1 on Python 3.7.1 and Windows 10.

Version 2.5.3 does not have the issue.  All versions afterward still fail with this problem.

For those trying to work around the issue due to a deep dependency generating the error, you can downgrade to version 2.5.3 (e.g. `pip install -Iv python-dateutil==2.5.3`).
