### ISSUE TITLE
Module not correctly loaded

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [dateutil/dateutil#199]
Hello,

I'm having trouble using this package : 
```
>>> from dateutil.easter import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'dateutil.easter'
```
I installed this package with pip. and it's file located in `/usr/lib/python3.5/site-packages/dateutil`, strangely, the folder only contains this:

```
drwxr-xr-x 3 root root 4.0K Mar  2 09:00 tz/
drwxr-xr-x 3 root root 4.0K Mar  2 09:02 zoneinfo/
```
and the package seems empty in the python REPL: 

```
>>> import dateutil
>>> dateutil.__
dateutil.__class__(         dateutil.__ge__(            dateutil.__lt__(            dateutil.__reduce_ex__(
dateutil.__delattr__(       dateutil.__getattribute__(  dateutil.__name__           dateutil.__repr__(
dateutil.__dict__           dateutil.__gt__(            dateutil.__ne__(            dateutil.__setattr__(
dateutil.__dir__(           dateutil.__hash__(          dateutil.__new__(           dateutil.__sizeof__(
dateutil.__doc__            dateutil.__init__(          dateutil.__package__        dateutil.__spec__
dateutil.__eq__(            dateutil.__le__(            dateutil.__path__           dateutil.__str__(
dateutil.__format__(        dateutil.__loader__         dateutil.__reduce__(        dateutil.__subclasshook__(
```

Any hints on how to install it ?

**Comment by pganssle** [comment]
@GuillaumeLeclerc What version of dateutil are you using?
```
$ python -c 'from dateutil import __version__; print(__version__); from dateutil.easter import *; print("Lookin good, Joey Lawrence")'
2.5.0
Lookin good, Joey Lawrence
```

Works fine for me with 2.5.0. Try `pip install --upgrade python-dateutil`, maybe?

**Comment by GuillaumeLeclerc** [comment]
DIdn't worked:

```
~> python -c 'from dateutil import __version__; print(__version__); from dateutil.easter import *; print("Lookin good, Joey Lawrence")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name '__version__'

```

**Comment by GuillaumeLeclerc** [comment]
```
> sudo pip install --upgrade python-dateutil
[sudo] password for guillaume: 
Requirement already up-to-date: python-dateutil in /usr/lib/python3.5/site-packages
Requirement already up-to-date: six>=1.5 in /usr/lib/python3.5/site-packages (from python-dateutil)
```

**Comment by pganssle** [comment]
@GuillaumeLeclerc Try `pip uninstall python-dateutil` then `pip install python-dateutil`, I guess. Evidently you have a malformed version of dateutil.

Alternately, maybe the python install that `sudo` is using to run `pip` is different than the one you use to run the script. You could try ```sudo `which pip` install --upgrade python-dateutil```.

**Comment by GuillaumeLeclerc** [comment]
I uninstalled the package and reinstalled and it worked ! 

Thank you, everything running fine :)

**Comment by pganssle** [comment]
Glad you got things working.
