### ISSUE TITLE
Version 2.5.0 does not parse string that 2.4.2 does

### ISSUE THREAD

**Issue by nixscripter** [dateutil/dateutil#203]
I really like dateutils, because it handles some really ugly corner cases for me, like this one:

```
>>> import dateutil
>>> print dateutil.__version__
2.4.2
>>> from dateutil import parser as date_parser
>>> example_date = '15/08/14,10:52:07-20q'  # what my application gives me -- totally non-standard
>>> date_parser.parse(example_date[:17])
datetime.datetime(2014, 8, 15, 10, 52, 7)
```

Or at least, it did until version 2.5.0:

```
>>> import dateutil
>>> print dateutil.__version__
2.5.0
>>> from dateutil import parser as date_parser
>>> example_date = '15/08/14,10:52:07-20q'
>>> date_parser.parse(example_date[:17])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/dateutil/parser.py", line 1161, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/lib/python2.7/site-packages/dateutil/parser.py", line 552, in parse
    raise ValueError("Unknown string format")
ValueError: Unknown string format
```
I hope this is easy to fix.

**Comment by pganssle** [comment]
@nixscripter Just curious, but is 15/08/14 supposed to represent August 14, 2015, or August 15, 2014?

The problem in that string is the `14,10`. I suspect it's related to PR #106.

**Comment by nixscripter** [comment]
@pganssle August 15, 2014 (otherwise, I would use ```yearfirst=True```). The 2.4.2 behavior is what I expect.

And while I didn't do a complete analysis, it does look like the culprit. I imagine it would be pretty difficult to make the state machine recover if it wasn't a number of milliseconds, so I don't know what to suggest.
