### ISSUE TITLE
parse() of datetime throws exception

### ISSUE THREAD

**Issue by adamn** [dateutil/dateutil#269]
If parse() is given a datetime, an AttributeError is thrown.  Ideally the datetime would simply be returned.

Alternately, a TypeError should be thrown with a message like 'parse() does not accept datetime'.

```python
>>> from dateutil.parser import parse
>>> parse('2016-05-12')
datetime.datetime(2016, 5, 12, 0, 0)
>>> parse(parse('2016-05-12'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/paul/.virtualenvs/pandas/local/lib/python2.7/site-packages/dateutil/parser.py", line 1164, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/paul/.virtualenvs/pandas/local/lib/python2.7/site-packages/dateutil/parser.py", line 552, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/home/paul/.virtualenvs/pandas/local/lib/python2.7/site-packages/dateutil/parser.py", line 671, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/home/paul/.virtualenvs/pandas/local/lib/python2.7/site-packages/dateutil/parser.py", line 188, in split
    return list(cls(s))
  File "/home/paul/.virtualenvs/pandas/local/lib/python2.7/site-packages/dateutil/parser.py", line 184, in next
    return self.__next__()  # Python 2.x support
  File "/home/paul/.virtualenvs/pandas/local/lib/python2.7/site-packages/dateutil/parser.py", line 177, in __next__
    token = self.get_token()
  File "/home/paul/.virtualenvs/pandas/local/lib/python2.7/site-packages/dateutil/parser.py", line 93, in get_token
    nextchar = self.instream.read(1)
AttributeError: 'datetime.datetime' object has no attribute 'read'
```

**Comment by pganssle** [comment]
@adamn This is already fixed in the master branch, it was issue #171, fixed in #247. It will be included in the 2.6.0 branch.

The new behavior will be that the parser will accept string types (`unicode`, `str` in Python 2.x or `str` and `bytes` in Python 3.x) or any object that implements the `read()` interface and returns characters. Passing anything else to the parser will raise a `TypeError`.

I don't think it makes sense to return a datetime if passed a datetime, since the point of the parser is to pass it a string, and it's probably not a good idea to just silently do nothing. End users can implement a wrapper around the parser that takes strings or datetimes if they want.
