### ISSUE TITLE
Can't compare offset-naive and offset-aware datetimes with rrulestr() in some cases

### ISSUE THREAD

**Issue by gelin** [dateutil/dateutil#341]
```
>>> from dateutil.rrule import rrulestr
>>> list(rrulestr("""
... DTSTART:20170101
... RRULE:FREQ=DAILY;UNTIL=20170102T120000Z
... """))
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/gelin/tmp/dateutil/lib/python3.5/site-packages/dateutil/rrule.py", line 860, in _iter
    if until and res > until:
TypeError: can't compare offset-naive and offset-aware datetimes
```

I've got calendar event where dtstart is offset-naive, while rrule until is offset-aware. In this case rrule fails to build the dates list.

Affected v.2.6.0 and v.2.4.2.

**Comment by pganssle** [comment]
@gelin Sorry for the delay in responding to this.

What exactly is the desired mitigation here? There's no rule for how to compare offset-naive datetimes with offset-aware datetimes. The options seem to be:

1. Convert `DTSTART` to `tzlocal()`
2. Convert `DTSTART` to `tzutc()`
3. Convert `DTSTART` to some other zone.
4. Convert `UNTIL` to naive.

You can see that 1, 2, and 3 are ambiguous with one another, and all three of those are ambiguous with 4. This seems to be a case of GIGO, and an error is appropriate.

**Comment by gelin** [comment]
@pganssle Technically this is error in the calendar event, I've got this only once with the event in Google Calendar created some years ago.
However, I think any error in data must not cause the library crash. But some data or precision loss is possible.
So, I vote for 4. If DTSTART is naive, all other datetime in event should be naive too.

**Comment by pganssle** [comment]
@gelin I disagree with the general principle that libraries should not crash on the event of malformed data. Otherwise, you end up silently coercing errors and downstream users have no way of finding out that their input data is malformed. Ideally, an upstream library like `dateutil` would provide an error that could be caught, and hopefully some way to recover from it.

The problem here is that `rrulestr` is parsing into an opaque structure, so there's no way to recover from this particular error without re-writing most of the `rrulestr` parser as a fallback for the main parser.

Possible options:
1. Expose the components of the `rrule` so that a user can conditionally modify the rule based on what gets parsed.
2. Expose a method like `rrulestr.to_kwargs` that parses the rrule into a `dict` that can be passed to `rrule`, allowing for modifications to the parsed components before construction.

I also think that this should fail during construction, not during evaluation of the rule. If we go that route, option 1 (which is more work anyway) is infeasible, since it would be impossible to create an `rrule` that could be modified anyway. Plus, option 1 would mean we'd have to expose the components of *all* `rrule`s, which isn't a *terrible* idea but it's a bit broader than the solution to this problem, so I think the right way to go is option 2 where an error is raised on mixture of timezone-naive and timezone-aware datetimes during construction.

**Comment by gelin** [comment]
@pganssle Ok. Agree that separation of parsing the rrule string from the evaluation of it can help here.
Option 2 looks good.

**Comment by hobarrera** [comment]
An alternative approach is to pass an optional `timezone` argument into `rrulestr`:

* If both `START` and `UNTIL` are tz-naive, it is unused.
* If both `START` and `UNTIL` are tz-aware, it is unused.
* If either of both is tz-naive, and the other is tz-aware, then set the timezone for the naive one to the value of the `timezone` argument.

This allows downstream users to "pick" between either (1), (2) and (3), but also keeps the GIGO default (eg: when no `timezone` is passed, keep the current behaviour), which really makes sense as the default behaviour (as has been mentioned earlier on this discussion).

---

The big downside I'm seeing it that timezones that come from `pytz` (I think we can all agree this is probably an extremely common scenario) can't be used like `dt.replace(tzinfo=tz)`, but rather need to be used like `tz.localize(dt)`. But a try/catch will probably fix this.

**Comment by pganssle** [comment]
@hobarrera I think that is really the job for a higher-level API than `dateutil`. I prefer something a bit closer to a thin wrapper API over the `rrule` RFC, so long as it's possible for it to be pythonic. I also think the API you've proposed is a bit hard to reason about - sometimes the `timezone` argument is used, sometimes it is used for tz-naive datetimes, but other times it's not - I don't think people will find it intuitive.

I think that my proposed option 2 is cleanest, because it allows end users to outsource both the `rrulestr` parsing *and* the `rrule` construction to `dateutil`, but still allows for modifications to the rule using python objects.

**Comment by hobarrera** [comment]
I think intuitiveness can be fixed by just calling it `fallback_timezone` (plus, good docs about it wouldn't hurt).

I'm not closed to alternatives though, but it's not 100% clear to me exactly how that proposal would work (or actually, what the API would be like). It does sound quite a bit more complex though.

**Comment by pganssle** [comment]
That helps with intuitiveness, but I still don't like it because it's an unnecessary addition to `rrule`. I'd rather have something that allows you to parse `rrule` strings and create `rrule` objects without feature creep where any additional changes that need to be made in between the parsing and the rule construction have to be implemented upstream in `dateutil`.

You even provide an example of why this is a problem:

> The big downside I'm seeing it that timezones that come from pytz (I think we can all agree this is probably an extremely common scenario) can't be used like dt.replace(tzinfo=tz), but rather need to be used like tz.localize(dt). But a try/catch would probably suffice for this.

This is exactly the sort of thing I'm worried about - I don't generally target `pytz`'s non-standard timezone interface, and I don't want to introduce a bunch of unnecessary coupling between `dateutil` and `pytz` or any other time zone library that decides to use its own funky `tzinfo` implementation. If I provide users an interface between the parsing step and the construction step (whether it's done through inheritance or composition in some modifiable intermediate object/dictionary), then users using `pytz` can use `tz.localize()` and users using `funkytz` can use `tz.beseech_the_dread_god_gnfathn(dt)` or whatever.

---

In terms of implementation, I guess you're right that the second one is a bit more complicated than I thought. I was thinking that `rrulestr` only generates `rrule` objects, but in fact it also generates `rruleset` objects, which does tend to complicate things. The problem there being that the constructor for `rruleset` doesn't really take arguments per se, so there's no good way to just present keyword arguments for constructing an `rruleset`. Even if we add keyword arguments to `rruleset`, you you now also have to return both the class that is to be constructed *and* the keyword arguments to construct it with.

It may be that exposing the contents of both `rrule` and `rruleset` is the simpler way to go in this case, though again that would prevent early failure detection since you'd have to allow an intermediate object to exist that doesn't have the right time zone properties.

I dunno, it may be worth making an exception to my "no feature creep" rule in this case, though I'm also toying around with the idea of making it easier to extend `rrulestr` so that people can easily inject their own code into various parts of the construction without too much effort.

**Comment by WhyNotHugo** [comment]
Isn't this fixed? Looks like this behaviour is covered by [this code](https://github.com/dateutil/dateutil/blob/master/dateutil/rrule.py#L455-L466), right?

**Comment by pganssle** [comment]
@WhyNotHugo True that that code now throws an error on construction, but I'm not sure that that solves the problem, since these strings cannot be parsed. Generally I think this comes up when someone is emitting invalid RRULE strings, and the consumer of these strings probably needs an "out" that allows them to handle non-compliant strings.

**Comment by pgcd** [comment]
I agree with @pganssle - that's exactly my scenario (I need to use RRULE strings generated by calendars with various degrees of compliance), and the code linked by @WhyNotHugo causes errors that I cannot handle in a satisfying way. 
I also find it rather confusing that the docs state that "missing values" will be extracted from dtstart: in my opinion, this suggests that missing timezone information is extracted from dtstart as well.
