### ISSUE TITLE
_naive_is_dst results in exception for negative epoch dates on windows

### ISSUE THREAD

**Issue by Prinz23** [dateutil/dateutil#434]
```python
import datetime
from dateutil import tz

dt = datetime.datetime.combine(datetime.date(1965, 11, 1), datetime.time(14, 0)).replace(tzinfo=tz.tzlocal())

dt.utcoffset()
```
this results on windows in exception:
```
Traceback (most recent call last):
  File "C:/git-tests/dateutil-test/test.py", line 6, in <module>
    dt.utcoffset()
  File "C:/git-tests/dateutil-test\dateutil\tz\tz.py", line 179, in utcoffset
    if self._isdst(dt):
  File "C:/git-tests/dateutil-test\dateutil\tz\tz.py", line 248, in _isdst
    dstval = self._naive_is_dst(dt)
  File "C:/git-tests/dateutil-test\dateutil\tz\tz.py", line 217, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')
```
reason is that **time.localtime()** doesn't support negative values on windows.

**Comment by pganssle** [comment]
@Prinz23 What time zone is this in?

**Comment by pganssle** [comment]
Hm.. This is actually an obvious failure in our test coverage. I'll make a separate issue for the testing part.

@Prinz23 One workaround is to use `tz.tzwin.tzwinlocal()` on Windows. I believe `tz.gettz()` will get the proper version of "local time zone" in a platform-independent way. There are other issues with using Python's `time` on Windows, which is why `tzwinlocal()` exists in the first place.

**Comment by pganssle** [comment]
Hm.. I thought it would return `tzwinlocal()` I wonder if that's a regression.

If you are going multi-platform, the workaround is this, I guess:

```python
def get_tzlocal():
   try:
        from from dateutil.tz.win import tzwinlocal
        return tzwinlocal()
    except ImportError:
        from dateutil.tz import tzlocal
        return tzlocal()
```

If you're targeting Windows only, then just `from dateutil.tz.win import tzwinlocal` and use that instead of `tzlocal()`.

**Comment by Prinz23** [comment]
calling tzlocal() results in an exception on my system:

```
Traceback (most recent call last):
  File "C:/git-tests/dateutil-test/test.py", line 5, in <module>
    t = tzwinlocal()
  File "C:/git-tests/dateutil-test\dateutil\tz\win.py", line 248, in __init__
    with winreg.OpenKey(handle, tzkeyname) as tzkey:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 67: ordinal not in range(128)
```

so can't use it.

**Comment by pganssle** [comment]
@Prinz23 What version of `dateutil` are you using?

**Comment by Prinz23** [comment]
94f1639b513280ca73144bc494d826616be22768 = current master

the problem here is that with python 2.7.x `winreg.OpenKey` is not fully unicode compatible and since my windows is german the timezone is called: 

`SOFTWARE\Microsoft\Windows NT\CurrentVersion\Time Zones\Mitteleuropäische Zeit`

and the `ä` in the regkey is the problem.

**Comment by wagner-certat** [comment]
Does it work with Python3?

**Comment by Prinz23** [comment]
Python3 gives the same UnicodeEncodeError. The registry info would not help anyways since windows timezone info starts at 1970-1-1.

Currently as workaround i use the `get_localzone` from `tzlocal` lib to get the real zoneinfo timezone name (windows has it's own names) and using this I'm loading the zoneinfo in dateutil.

Ideally dateutil would itself have the mapping (windows timezone names to zoneinfo names) function included and would load the the info from zoneinfo itself.

```python
import datetime
from dateutil import tz
from tzlocal import get_localzone

dt = datetime.datetime.combine(datetime.date(1965, 11, 1), datetime.time(14, 0)).replace(tzinfo=tz.gettz(get_localzone().zone))

dt.utcoffset()
```

this works. 

But is double work since `get_localzone` already returns the zoneinfo file, but it's own. So this would work too:

```python
dt = datetime.datetime.combine(datetime.date(1965, 11, 1), datetime.time(14, 0)).replace(tzinfo=get_localzone())
```

So would have to maintain both lib zoneinfo data. That is the reason i use the name returned from it to load the zoneinfo from dateutil.

**Comment by pganssle** [comment]
It's a bit surprising that the crash is happening still on Python 3.x. See the open bug #210 for the `tzwinlocal()` crash issue.

**Comment by Prinz23** [comment]
Oops, my bad. On python 3 it's not a UnicodeEncodeError, it's a `FileNotFoundError`. So i guess wrong string encoding used to access the reg key.

**Comment by Prinz23** [comment]
Ahh the wrong value (localized name) is used to open the regkey. This regkey doesn't even exists. 

After changing in `win.py`:
```python
self._std_abbr = keydict["StandardName"]
```
to the real keyname (which is always english apparently):
```python
self._std_abbr = keydict["TimeZoneKeyName"]
```
`tzwinlocal()` is working on python2 and 3. Since there is no unicode in the real regkey names (english names).

**Comment by Prinz23** [comment]
Apparently this key `TimeZoneKeyName` only exists on Windows 7+. 

See: https://github.com/regebro/tzlocal/blob/master/tzlocal/win32.py

And to solve the problem with pre 1970 dates the same mapping functionally that is used in that lib will have to be used to get the zone info from the zoneinfo file. (Native timezone info from the registry doesn't have pre 1970 timezone info)

**Comment by pganssle** [comment]
I'm not sure why I would want to pull the English name for the local string, we should just fix or work around the issue with `winreg`. That said, if you want to continue commenting on the unicode bug with `tzwinlocal`, issue #210 is more appropriate. This issue is tracking the `tzlocal()` issue, which is unrelated.

**Comment by Prinz23** [comment]
We also need to `tzwinlocal()` to work and it as to return `TimeZoneKeyName` regardless with which method it found the regkey/english name, so that then this value can be mapped via the list:
`http://unicode.org/repos/cldr/trunk/common/supplemental/windowsZones.xml`
to the real zonefile names. Now with that mapped name the `gettz()` can fetch the real zonefile info. 

Also the zoneinfo data that is include in the lib should be prioritized over the OS data for this to work correctly. OS zoneinfo data is many times outdated or simply not correct. Alternatively a parameter could be added to the gettz() function to prioritize the included zoneinfo data.

**Comment by pganssle** [comment]
It occurs to me that, in general, it might not be the best idea to use `tzlocal` for pre-1970 dates, *especially* on Windows (`tzwinlocal()` also wouldn't help). Windows time zones are not accurate, historically, they just represent the *current* rules for a given zone.

Presumably this shouldn't be throwing an error, at least not this way, if it can be helped, but it's not particularly likely to be accurate. If you want historical data, you should probably be using the `tzfile` files from the Olson database - and even those aren't guaranteed to be accurate pre-1970 (they maintain the pre-1970 zones, but it's on a "buyer beware" basis).

**Comment by Jacob-Bishop** [comment]
Any progress on this issue? I just ran into it when trying to convert a Pandas dataframe to a Spark dataframe in python 3.7 and dateutil 2.8.1.

**Comment by Prinz23** [comment]
I in the end fixed it for Windows 7+. I added to the win.py:

```python 
import sys
```
and changed the line from:
```python
self._std_abbr = keydict["StandardName"]
```
to:
```python
# only windows 7+ has the "TimeZoneKeyName" reg key
self._std_abbr = keydict["TimeZoneKeyName" if (6, 1) <= sys.getwindowsversion()[:2] else "StandardName"]
```

This way the buggy behavior will still stay the same for pre Windows 7 os, but it's fixed for all newer. And personally for the projects i work on think user that use OS's who's support has been dropped (for years in case of pre 7) have to live with bugs.

**Comment by Jacob-Bishop** [comment]
@Prinz23 Great, thanks! I'll be on the lookout for version 2.8.2.
