### ISSUE TITLE
tzwinlocal crashing on pypy

### ISSUE THREAD

**Issue by pganssle** [dateutil/dateutil#448]
Included this here, originally reported on the [pypy issue tracker, issue 2632](https://bitbucket.org/pypy/pypy/issues/2632/dateutil-tztzwinlocal-from-datetime-not#comment-39126530):

> When I try to use tz.tzwinlocal from datetime, I get the following error:
```python
Python 2.7.13 (c925e7381036, Jun 06 2017, 05:28:16)
[PyPy 5.8.0 with MSC v.1500 32 bit] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>> from dateutil import tz
>>>> x = tz.tzwinlocal()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\pypy2-v5.8.0-win32\site-packages\dateutil\tz\win.py", line 241, in __init__
    keydict = valuestodict(tzlocalkey)
  File "c:\pypy2-v5.8.0-win32\site-packages\dateutil\tz\win.py", line 330, in valuestodict
    value = tz_res.name_from_string(value)
  File "c:\pypy2-v5.8.0-win32\site-packages\dateutil\tz\win.py", line 113, in name_from_string
    return self.load_name(offset)
  File "c:\pypy2-v5.8.0-win32\site-packages\dateutil\tz\win.py", line 82, in load_name
    nchar = self.LoadStringW(self._tzres._handle, offset, lpBuffer, 0)
  File "c:\pypy2-v5.8.0-win32\lib_pypy\_ctypes\function.py", line 349, in __call__
    self._convert_args(argtypes, args, kwargs))
  File "c:\pypy2-v5.8.0-win32\lib_pypy\_ctypes\function.py", line 577, in _convert_args
    raise ArgumentError(str(e))
ArgumentError: expected c_void_p instance instead of alt.WinDLL
>>>>
```
> Above code works fine with a standard Python 2.7.13 installation (Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32). My machine runs Windows Server 2008 R2 64-bit.

This may be an issue with pypy, but I'm wondering if we're supposed to be accessing `._handle` on `self._tzres`, since it looks like that's part of the private interface.

**Comment by pganssle** [comment]
This is [possibly fixed over there](https://bitbucket.org/pypy/pypy/commits/141ba627dc5f), but I can't really tell if it's fixed because it would involved building Pypy3 from master on Windows - and I have trouble enough just running dateutil against Windows *binaries*, so it will take some more investigation.

To me, it's still not clear if *we're* not supposed to be accessing `_handle` or if `pypy`'s implementation of `ctypes` was setting `_handle` incorrectly.
