### ISSUE TITLE
datetime exception while parsing unambiguous string

### ISSUE THREAD

**Issue by WeatherGod** [dateutil/dateutil#487]
```
>>> date_str
'1237 PM EDT Mon Oct 30 2017'
>>> dateutil.parser.parse(date_str)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/broot/scratch/miniconda/lib/python2.7/site-packages/dateutil/parser.py", line 1182, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/broot/scratch/miniconda/lib/python2.7/site-packages/dateutil/parser.py", line 581, in parse
    ret = default.replace(**repl)
ValueError: hour must be in 0..23
```

As a side-note, is there ever going to be an option for end-users to specify a format string for parsing? In this case, `dateutil` is really the only good option for easily handling arbitrary timezones (I don't know ahead of time which timezone a string will have), but I have always been antsy about the lack of control over the parser, because in this case, I know that my date string will always follow this particular form.

**Comment by pganssle** [comment]
This one is a bit weird partially because apparently it's choosing the wrong thing for the hour, but I think at the moment it would be quite hard to support this kind of string, mostly because we don't necessarily have a way to distinguish between `1237` and `2017` as the year (though in this case we *could* theoretically distinguish it because October 30, 1237 was a Thursday).

In this case, since you know the format, I recommend doing something like this:

```python
from datetime import datetime
from dateutil import tz

def parse_specific_string(dtstr):
    dt = datetime.strptime(dtstr, '%H%M %p %Z %a %b %d %Y')
    tzname = dtstr[8:].split(' ', 1)[0]
    if tzname:
        tzi = tz.gettz(tzname)
        dt = dt.replace(tzinfo=tzi)

    return dt
```

I would then take the person who decided to use `'%H%M %p %Z %a %b %d %Y'` as a string format and give them a stern talking-to. I think `%Z` may only be "supported" for Python 3, and even then it really just ignores that section of the string. No matter how you slice it, though, it's risky business using the 3-letter time zone name abbreviations to actually get a time zone name.

**Comment by jbrockmendel** [comment]
This is a class of cases that I intend to fix, but its not high on the priority list.  As @pganssle mentioned, its a re-write as opposed to a bug-fix.

One way you could help keep this from drifting down the todo list would be to submit a PR creating a test for this case marked as `xfail`.

**Comment by pganssle** [comment]
I'm going to be honest, I don't love `xfail` tests, but I am willing to be persuaded about that.

**Comment by WeatherGod** [comment]
@jbrockmendel I can certainly create such a pull request to add an expected fail. I'll put it together shortly.

@pganssle would you all be interested if I made a PR that supplied a function kind of like that, but which would search the format string for `%Z` (and/or `%z` for python 2.7) and tries to automatically create a timezone-aware datetime object?

**Comment by pganssle** [comment]
@WeatherGod By the way, I'm sorry I didn't address your other question yesterday. Regarding specifying the format, I'd say that I have some ideas for moving in this direction, but in some ways, I'm not entirely sure that `dateutil.parser.parser` is the right thing to make particularly strict like that. I think that is in contrast to its "auto-magical" properties, and honestly for the most part if you know the format of the string, you should probably be using `datetime.strptime`. The main problem is that format strings are a fairly limited DSL and don't allow any sort of conditional evaluation, but as you go down the road of making more and more configurations, you end up with a fairly complicated language that has grown organically - a very dangerous situation from a design perspective.

In my head I'm playing around with the idea of a parser that first breaks the string down into an intermediate representation from which a date could be parsed, and then uses that to parse the date. I think adding in this "intermediate representation" seam could then be useful for specifying various aspects of how you want your date parsed.

That said, I don't know how feasible that would be. There's a lot of weird stuff about the context of the string that may make it very difficult to represent in the abstract in a way that can be easily exposed downstream.

**Comment by WeatherGod** [comment]
Ah, true, that would be tricky. Perhaps one could take inspiration from the regex language for conditional evaluation? While regex's aren't ideal, they are well-documented and borrowing concepts from it could make it easier tor others to grok.

**Comment by pganssle** [comment]
> Would you all be interested if I made a PR that supplied a function kind of like that, but which would search the format string for %Z (and/or %z for python 2.7) and tries to automatically create a timezone-aware datetime object?

I'll note that this is actually harder than you'd think. For example, imagine I re-arrange the string above so that it can actually get parsed - look at the behavior between `EDT` and `CST`:

```python
>>> from dateutil.parser import parse
>>> parse('Mon Oct 30, 2017 12:37 PM EDT')
datetime.datetime(2017, 10, 30, 12, 37, tzinfo=tzlocal())
>>> parse('Mon Oct 30, 2017 12:37 PM CST')
datetime.datetime(2017, 10, 30, 12, 37)
```

The first one works because my local `time.tzname` happens to have `EDT` in it, so the parser assumes that's what was meant, but it has no reference for `CST`, and [CST is overloaded](https://www.timeanddate.com/time/zones/#anc-3), it could mean Central Standard Time, China Standard Time or Cuba Standard Time. In general, these 3-letter offset abbreviations are not unique and require context to disambiguate. I imagine this is the reason that `%Z` doesn't work in `strptime`.

That said, I don't think it's inherently a bad idea to have a slightly-more-functional `strptime` that uses the same `tzinfos` approach [used by `dateutil.parser.parse`](https://dateutil.readthedocs.io/en/latest/parser.html#dateutil.parser.parse) and backports the `%z` functionality is not a bad idea. It might be interesting to look at the discussion in `python-dev` to see if they came up with this solution, and if not whether it would be worth proposing for `datetime.strptime`.

**Comment by WeatherGod** [comment]
Personally, I would be happy if `%Z` just simply captured the string and
still gives me back a timezone naive datetime object, just with `tzname`
populated. I can then convert it into a timezone-aware object.

**Comment by pganssle** [comment]
I think that would be quite confusing, because you can't just populate `tzname` - that's a *function* on `tzinfo`, so you'd have to attach a `tzinfo` with some constant `tzname` but presumably invalid values for DST and offset. `tzinfos` takes a dictionary or *callable*, though, so you can pass it a function that takes the `tzname` and returns a time zone.

**Comment by WeatherGod** [comment]
talk about confusing.... just realized that `%Z` chokes on 'EDT', but not 'EST' (at least, on py27). Why did python do a half-baked implementation of `%Z` and `%z`?!? Kinda feel like Charlie Brown running to kick the football...
