### ISSUE TITLE
Parser quirks in ISO8601 formats

### ISSUE THREAD

**Issue by TimSC** [dateutil/dateutil#531]
A few issues I have with 3e76cb6b and ISO8601 formats:

* Parsing "2009-05" gives me: datetime.datetime(2009, 5, 24, 0, 0) which seems wrong. I'd expect datetime.datetime(2009, 5, 1, 0, 0)
* Parsing "2007-04-05T24:00" fails but I think this is a valid format.
* Parsing "2010-02-18T16.2" fails but I think this is a valid format.

I suggest these are added to the automatic tests. Most of these cases come from this blog post [https://www.myintervals.com/blog/2009/05/20/iso-8601-date-validation-that-doesnt-suck/] and it would be worth considering testing for as many as possible (I have not checked dateutil comprehensively against them).

**Comment by pganssle** [comment]
The first issue is not an issue, just an unfortunate choice (in my opinion) that was made in the original parser implementation. The current behavior is that *all* missing components are filled in from the `default` date, which defaults to today. Off the top of my head, I'd say a better implementation would be if all missing components *larger* than the largest present component were filled in from the default date, and all missing components *smaller* than that would be filled in with the minimum value in that field. That said, that would be a major API change, and I'm not going to do it without a pretty long deprecation cycle with an option to default to the old behavior.

If you know you're parsing ISO8601 datetimes (not including bare ISO-8601 times), you can probably get something equivalent to this with this: `parse(dt_str, default=datetime(datetime.now().year, 1, 1))`, since the only ISO-8601 format without a year is `--MM-DD`.

Regarding the other two:

1. We should probably support `24:00` as an alias for `0:00`. That may be a bit more complicated than it sounds.
2. That's a fairly uncommon ISO-8601 format, in my experience, and I think not a great one. Technically there are fractional time components (e.g. `parse('2010-02-18 16.2h')`), so this may be a bug, but again it may be difficult to handle because I'm not 100% clear on what situations will allow that `16` to be unambiguously detected as an hour.

The dedicated ISO-8601 parser does not have the same choice of default behavior, and it does support `24:00` as an alias for midnight. It will likely eventually support fractional time components as well.

**Comment by cjgibson** [comment]
Didn't want to open a new issue, but commenting here to note another _potential_ oddity:

```python
$ python -c "from dateutil.parser import parse
> print parse('1970-01-01T00:00:00Z')
> print parse('1970-01-01t00:00:00Z')
> print parse('1970-01-01t00:00:00')
> print parse('1970-01-01t00:00:00z')"
1970-01-01 00:00:00+00:00
1970-01-01 00:00:00+00:00
1970-01-01 00:00:00
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 1182, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 559, in parse
    raise ValueError("Unknown string format")
ValueError: Unknown string format
```

I personally hadn't observed a lowercase "Z" before, but from what I can tell, the standard allows for it. (At least, going off of this RFC: https://tools.ietf.org/html/rfc3339#section-5.6)

**Comment by pganssle** [comment]
@cjgibson Can you make a separate issue? I prefer to have separate issues so tickets can be assigned individually and be closed as they are addressed.

**Comment by cjgibson** [comment]
@pganssle - Can do.
