### ISSUE TITLE
Fatal error installing 2.7.1

### ISSUE THREAD

**Issue by AdamIsrael** [dateutil/dateutil#657]
I encountered the following error while building a docker container that uses python-dateutil:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 243, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 273, in run
    return func()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 242, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-ng1ftzdf/python-dateutil-2.7.1/setup.py", line 44, in <module>
    license='Apache 2',
  File "/tmp/easy_install-ng1ftzdf/python-dateutil-2.7.1/setup.py", line 31, in README
    exclude=["*.tests", "*.tests.*", "tests.*", "tests"]),
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4037: ordinal not in range(128)
```

The full output is [here](https://paste.ubuntu.com/p/vJQpb6jWQ4/).

It looks like an encoding issue, with a non-ascii character in the README, but it looks like this was fixed in commit f39c1ae6fb6082464077d681fdc80a4ab3679466 several hours ago. Is there an ETA on a new release?

**Comment by pganssle** [comment]
2.7.2 release is now out with this fixed.
