### ISSUE TITLE
ModuleNotFoundError: No module named 'dateutil._common'

### ISSUE THREAD

**Issue by jackiehff** [dateutil/dateutil#719]
when i execute 'import matplotlib.pyplot as plt', I got following error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jackiehff/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 39, in <module>
    from matplotlib.figure import Figure, figaspect
  File "/Users/jackiehff/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py", line 40, in <module>
    from matplotlib.axes import Axes, SubplotBase, subplot_class_factory
  File "/Users/jackiehff/anaconda3/lib/python3.6/site-packages/matplotlib/axes/__init__.py", line 4, in <module>
    from ._subplots import *
  File "/Users/jackiehff/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_subplots.py", line 10, in <module>
    from matplotlib.axes._axes import Axes
  File "/Users/jackiehff/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 24, in <module>
    import matplotlib.dates as _  # <-registers a date unit converter
  File "/Users/jackiehff/anaconda3/lib/python3.6/site-packages/matplotlib/dates.py", line 152, in <module>
    from dateutil.rrule import (rrule, MO, TU, WE, TH, FR, SA, SU, YEARLY,
  File "/Users/jackiehff/anaconda3/lib/python3.6/site-packages/dateutil/rrule.py", line 23, in <module>
    from ._common import weekday as weekdaybase
ModuleNotFoundError: No module named 'dateutil._common'`
```

**Comment by pganssle** [comment]
I have no idea what could cause this. It seems like some sort of version inconsistency, but the only thing calling `dateutil._common` would be `dateutil` itself, so the only way I can imagine this occuring is if you installed *half* of `dateutil`.

@jackiehff Can you try `pip install -U python-dateutil` or `pip uninstall python-dateutil` followed by `pip install python-dateutil` and see if this fixes the problem for you?

**Comment by jackiehff** [comment]
@pganssle It seems like my upgrade operation hasn't finished correctly，then I use "sudo pip install -U python-dateutil" command and it worked! Really appreciate for your help!

**Comment by harshit112233** [comment]
yes it is working thank you soo much
