### ISSUE TITLE
setup.py has both requires and install_requires, leading to invalid metadata

### ISSUE THREAD

**Issue by mhsmith** [dateutil/dateutil#720]
Both the deprecated `requires` and the current `install_requires` are used:

https://github.com/dateutil/dateutil/blob/ad9807375b0f524cb9cef38abac70cacee693d36/setup.py#L65-L67

This results in the following lines in the wheel's METADATA file:

```
Requires: six
Requires-Dist: six (>=1.5)
```

distlib rejects this file as having an inconsistent set of headers:

```
>>> from distlib.database import InstalledDistribution
>>> InstalledDistribution("python_dateutil-2.7.3.dist-info")
Attempting to set metadata for <LegacyMetadata python-dateutil 2.7.3>
Removed 1.0 due to Maintainer
Removed 1.1 due to Maintainer
Removed 1.2 due to Description-Content-Type
Removed 2.0 due to Description-Content-Type
Removed 1.3 due to Requires
Removed 2.1 due to Requires
Out of options - unknown metadata set: {u'Maintainer': u'Paul Ganssle', u'Name': u'python-dateutil', u'License': u'Dual License', u'Author': u'Gustavo Niemeyer', u'Requires-Python': u'>=2.7, !=3.0.*, !=3.1.*, !=3.2.*', u'Requires-Dist': [u'six (>=1.5)'], u'Maintainer-email': u'dateutil@python.org', u'Metadata-Version': u'2.1', u'Home-page': u'https://dateutil.readthedocs.io', u'Description-Content-Type': u'text/x-rst', u'Platform': [u'UNKNOWN'], u'Version': u'2.7.3', u'Summary': u'Extensions to the standard Python datetime module', u'Requires': [u'six'], u'Classifier': [u'Development Status :: 5 - Production/Stable', u'Intended Audience :: Developers', u'License :: OSI Approved :: BSD License', u'License :: OSI Approved :: Apache Software License', u'Programming Language :: Python', u'Programming Language :: Python :: 2', u'Programming Language :: Python :: 2.7', u'Programming Language :: Python :: 3', u'Programming Language :: Python :: 3.3', u'Programming Language :: Python :: 3.4', u'Programming Language :: Python :: 3.5', u'Programming Language :: Python :: 3.6', u'Programming Language :: Python :: 3.7', u'Topic :: Software Development :: Libraries'], u'Author-email': u'gustavo@niemeyer.net'}
Traceback (most recent call last):
[...]
  File "/home/smith/.virtualenvs/pypi/lib/python3.6/site-packages/distlib/database.py", line 555, in __init__
    metadata = Metadata(fileobj=stream, scheme='legacy')
  File "/home/smith/.virtualenvs/pypi/lib/python3.6/site-packages/distlib/metadata.py", line 737, in __init__
    scheme=scheme)
  File "/home/smith/.virtualenvs/pypi/lib/python3.6/site-packages/distlib/metadata.py", line 281, in __init__
    self.read_file(fileobj)
  File "/home/smith/.virtualenvs/pypi/lib/python3.6/site-packages/distlib/metadata.py", line 381, in read_file
    self.set_metadata_version()
  File "/home/smith/.virtualenvs/pypi/lib/python3.6/site-packages/distlib/metadata.py", line 287, in set_metadata_version
    self._fields['Metadata-Version'] = _best_version(self._fields)
  File "/home/smith/.virtualenvs/pypi/lib/python3.6/site-packages/distlib/metadata.py", line 165, in _best_version
    raise MetadataConflictError('Unknown metadata set')
distlib.metadata.MetadataConflictError: Unknown metadata set
```

This didn't happen with previous versions of dateutil, because they contained a metadata.json, which distlib prefers and parses in a different way. But the recent dateutil version 2.7.3 doesn't contain the metadata.json.

distlib exists primarily as a component of pip, and seems to be rarely used elsewhere. pip itself isn't currently affected by this problem, because it parses the METADATA file using `pkg_resources` instead. However, I wouldn't be surprised if that changed in the future, in which case new versions of pip would be unable to install this version of dateutil.

Anyway, the solution is to remove the "requires" line. It's been deprecated since PEP 345, 13 years ago, and as far as I can tell, pip completely ignores it.

**Comment by pganssle** [comment]
@mhsmith Thanks for the report! I think you are right. The hard part of any PR on this would be writing a regression test for it, but I think we can probably just skip that.

**Comment by mhsmith** [comment]
The current version of the metadata specification is at https://packaging.python.org/specifications/core-metadata/. 

The only plausible regression test I can think of is to perform an install of the dateutil wheel with whatever you consider to be the minimum reasonable version of pip (or other packaging tool), and check that it still installs six even with that line removed.

**Comment by cssherry** [comment]
I can take
