### ISSUE TITLE
tzname assumes there is a good name?

### ISSUE THREAD

**Issue by sontek** [dateutil/dateutil#74]
```
from dateutil.parser import parse
dt = parse('2010-07-15T17:58:00-07:00')
dt.tzname()
```

and I get this exception:

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    dt.tzname()
  File "/home/sontek/venvs/monkeylib/src/MonkeyLib/.tox/py27/local/lib/python2.7/site-packages/dateutil/tz.py", line 41, in inner_func
    return myfunc(*args, **kwargs).encode()
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by pganssle** [comment]
@sontek Easy enough to fix - I'm thinking that the desired behavior here is no error thrown, returning None?

**Comment by sontek** [comment]
@pganssle yeah, that would work perfectly for me
