### ISSUE TITLE
dateutil can't parse "2018-08-14 08:41:31.181 1288 ERROR"

### ISSUE THREAD

**Issue by ignatenkobrain** [dateutil/dateutil#803]
```python
Traceback (most recent call last):
  File "l.py", line 56, in <module>
    main()
  File "l.py", line 51, in main
    print(dateutil.parser.parse("2018-08-14 08:41:31.181 1288 ERROR", fuzzy_with_tokens=True))
  File "/usr/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 1301, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 607, in parse
    raise ValueError("Unknown string format:", timestr)
ValueError: ('Unknown string format:', '2018-08-14 08:41:31.181 1288 ERROR')
```

**Comment by jbrockmendel** [comment]
What is the "1288" supposed to be?

**Comment by ignatenkobrain** [comment]
@jbrockmendel sorry for not including this information. It's pid of process =)

**Comment by jbrockmendel** [comment]
Got it, thanks.  Short term your best best is to strip off the PID and the "ERROR".  Medium-term I'll take a look at fixing this.  PRs welcome.
