### ISSUE TITLE
Should tz.gettz() return tzwinlocal on Windows?

### ISSUE THREAD

**Issue by pganssle** [dateutil/dateutil#848]
[`tzwinlocal`](https://dateutil.readthedocs.io/en/latest/tz.html#dateutil.tz.tzwinlocal) is a different kind of local time object, and one that works much better in many respects on Windows. There was a suggestion in #197 to make `tz.tzwinlocal` the implementation for `tz.tzlocal` on Windows, but I think that is probably a bridge too far.

One thing we *can* do, however (and I will consider this a breaking change, so it's in the 3.0 bucket), is make `tz.gettz()` return a `tz.tzwinlocal` object. If we're confident that `tz.tzwinlocal` is the better option, that should be prioritized above `tz.tzlocal` when available.

Upsides of `tz.tzwinlocal`:

- Works on Windows when the system time zone is changed during the execution of a program
- Not susceptible to #197 
- Possibly faster? (Will need to benchmark this)

Downsides of switching the default:

- Because it's *not* the default, `tz.tzwinlocal` is probably much less widely used than `tz.tzlocal`, and thus is more likely to have bugs we haven't seen
- May not work with non-ASCII time zone names: #210 (possibly this can be fixed by falling back to `tz.tzlocal` if we can't easily fix #210).

This ticket also can be somewhat dramatically affected by how we decide to resolve #668 (see the note on `tz.tzlocal` and `tz.tzwinlocal`), since the two may end up with different caching behaviors.

Still, on balance I'm in favor of making the change.

**Comment by labrys** [comment]
@pganssle Would a `tz.tzlocal` from Windows generally compare equal to a `tz.tzlocal` from Linux?

**Comment by pganssle** [comment]
@labrys I'm not sure if they compare equal, but equality is not super important in `tzinfo` objects, since the [semantics of `datetime` use `is` rather than `==`](https://blog.ganssle.io/articles/2018/02/a-curious-case-datetimes.html).

I will be speaking at the PyCon Language Summit on Wednesday about adding time zones to the standard library (see [my slides](https://pganssle-talks.github.io/pycon-us-2019-language-summit-tz/#/)). Part of the pitch is adding a "local" object. How that turns out may influence what we want to do with this ticket.

**Comment by labrys** [comment]
@pganssle Poor choice of words.  By compare I don't mean the comparison operators, I mean same available interface that can generally be expected to produce the same results on more than one platform.

For example, you have listed one of the upsides of `tz.tzwinlocal` as:
> Works on Windows when the system time zone is changed during the execution of a program

Does `tz.tzlocal` do this on Linux?  If not this would be a fundamental difference in how `tzlocal` and `tzwinlocal` behave and one might prefer to enforce `tzlocal` on both to get consistent behaviour.

**Comment by jwilges** [comment]
@pganssle did you get a chance to look into this any further? `botocore.utils.parse_timestamp` still has a prime example of where an OS-sensitive `gettz()`-style `tzlocal()` lookup would be beneficial:

```python
# botocore.utils.parse_timestamp, today:
datetime.datetime.fromtimestamp(value, tzlocal())
# if gettz() becomes OS-conditional, upstream maintainers can adopt:
datetime.datetime.fromtimestamp(value, gettz())
```

I realize this might be an oversimplification of the issue but I want to believe there's a reasonable path forward for upstream libraries to adopt a change along these lines that works well enough until any issues at large are sorted out.

I don't typically have my head this far in **dateutil** or **botocore**, but when switching to test a service on a Windows system promptly threw this in my face it caught me by surprise enough to start investigating the issue.

## PST, Windows 10, Python 3.8.2, dateutil 2.8.1
Today, on Windows, this operation with `tzlocal()` fails marvelously:

```
>>> tzlocal().__dict__
{'_std_offset': datetime.timedelta(days=-1, seconds=57600), '_dst_offset': datetime.timedelta(days=-1, seconds=61200), '_dst_saved': datetime.timedelta(seconds=3600), '_hasdst': True, '_tznames': ('Pacific Standard Time', 'Pacific Daylight Time')}
>>> tzwinlocal().__dict__
{'_std_abbr': 'Pacific Standard Time', '_dst_abbr': 'Pacific Daylight Time', '_display': '(UTC-08:00) Pacific Time (US & Canada)', '_std_offset': datetime.timedelta(days=-1, seconds=57600), '_dst_offset': datetime.timedelta(days=-1, seconds=61200), '_stdmonth': 11, '_stdweeknumber': 1, '_stdhour': 2, '_stdminute': 0, '_stddayofweek': 0, '_dstmonth': 3, '_dstweeknumber': 2, '_dsthour': 2, '_dstminute': 0, '_dstdayofweek': 0, '_dst_base_offset_': datetime.timedelta(seconds=3600), 'hasdst': True}
>>> datetime.datetime.fromtimestamp(-3600, tzwinlocal())
datetime.datetime(1969, 12, 31, 15, 0, tzinfo=tzwinlocal())
>>> datetime.datetime.fromtimestamp(-3600, tzlocal())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".venv\lib\site-packages\dateutil\tz\_common.py", line 144, in fromutc
    return f(self, dt)
  File ".venv\lib\site-packages\dateutil\tz\_common.py", line 258, in fromutc
    dt_wall = self._fromutc(dt)
  File ".venv\lib\site-packages\dateutil\tz\_common.py", line 238, in _fromutc
    dtdst = enfold(dt, fold=1).dst()
  File ".venv\lib\site-packages\dateutil\tz\tz.py", line 232, in dst
    if self._isdst(dt):
  File ".venv\lib\site-packages\dateutil\tz\tz.py", line 292, in _isdst
    dstval = self._naive_is_dst(dt)
  File ".venv\lib\site-packages\dateutil\tz\tz.py", line 261, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
OSError: [Errno 22] Invalid argument
```

## PST, Docker python:3.8-slim, dateutil 2.8.1
On Linux, `tzlocal()` aligns with `tzwinlocal()`'s behavior from above:

```
>>> tzlocal().__dict__
{'_std_offset': datetime.timedelta(days=-1, seconds=57600), '_dst_offset': datetime.timedelta(days=-1, seconds=61200), '_dst_saved': datetime.timedelta(seconds=3600), '_hasdst': True, '_tznames': ('PST', 'PDT')}
>>> datetime.datetime.fromtimestamp(-3600, tzlocal())
datetime.datetime(1969, 12, 31, 15, 0, tzinfo=tzlocal())
```
