### ISSUE TITLE
Parsing error for "... PST8PDT"

### ISSUE THREAD

**Issue by maozguttman** [dateutil/dateutil#849]
Starting from dateutil 2.7.0 (and also: 2.7.1, 2.7.2, 2.7.3, 2.7.4 and 2.7.5) date parsing of example below is failing. It worked with dateutil 2.6.1. Using Python 2.7.15.

Example:
```
import datetime
import dateutil.parser
s = "Mon Feb 23 13:14:24 2015 PST8PDT"
d = dateutil.parser.parse( s, ignoretz = True, fuzzy = True )
print d
```
Error:
```
Traceback (most recent call last):
  File "try.py", line 4, in <module>
    d = dateutil.parser.parse( s, ignoretz = True, fuzzy = True )
  File "/usr/python/2.7.15/lib/python2.7/site-packages/dateutil/parser/_parser.py", line 1356, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/python/2.7.15/lib/python2.7/site-packages/dateutil/parser/_parser.py", line 648, in parse
    raise ValueError("Unknown string format:", timestr)
ValueError: (u'Unknown string format:', 'Mon Feb 23 13:14:24 2015 PST8PDT')
```

**Comment by jbrockmendel** [comment]
"PST8PDT" is definitely not a format the parser will recognize.  Where does this example come from?

**Comment by shirotman** [comment]
dateutil 2.8.0-2.8.2 (latest) are also still failing to parse it
