### ISSUE TITLE
Feature request: support specifiying time zone by full name

### ISSUE THREAD

**Issue by vr2262** [dateutil/dateutil#93]
`dateutil.parser.parse` can parse all the time formats acceptable to Postgres except for this one:

`2003-04-12 04:05:06 America/New_York`

(from http://www.postgresql.org/docs/9.4/static/datatype-datetime.html#DATATYPE-DATETIME-TIME-TABLE)

```python
>>> import dateutil.parser
>>> dateutil.parser.parse('2003-04-12 04:05:06 America/New_York')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/viktor/.virtualenvs/rewrite/lib/python3.4/site-packages/dateutil/parser.py", line 748, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/viktor/.virtualenvs/rewrite/lib/python3.4/site-packages/dateutil/parser.py", line 310, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
TypeError: 'NoneType' object is not iterable

```

I tried passing a dictionary for the `tzinfos` parameter with a key for `'America/New_York'`, but it fails with the same error. I believe it fails because of the non-ASCII characters (/ and _) in the time zone.

**Comment by aschatten** [comment]
@pganssle I have a PR #150 that could fix the issue.

**Comment by batterseapower** [comment]
So just to summarize the state of play for anyone else coming across this issue, it looks like there *was* an implmentation of this feature in 2016 in PR #227 (which was- based on #150 and #153 by @aschatten), but it never got merged in. So there is still no way to do this as of dateutil 2.8.1, the most recent version as of the time of writing.

(The PR was closed without comment in 2018, probaby because it had got hopelessly behind master.)
