### ISSUE TITLE
Fail to parse "2018-12-10 17:55:02 (GMT+0:00)"

### ISSUE THREAD

**Issue by lorien** [dateutil/dateutil#930]
```
lorien@air:/web/whois_tools$ pip3 freeze | grep dateutil
python-dateutil==2.7.3

lorien@air:/web/whois_tools$ python3 -c 'from dateutil.parser import parse; parse("2018-12-10 17:55:02 (GMT+0:00)")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/dateutil/parser/_parser.py", line 1356, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/dateutil/parser/_parser.py", line 648, in parse
    raise ValueError("Unknown string format:", timestr)
ValueError: ('Unknown string format:', '2018-12-10 17:55:02 (GMT+0:00)')
```

**Comment by mbdevpl** [comment]
Seems related to or duplicate of #453.

Using `dateutil.parser.parse('2018-12-10 17:55:02 (GMT+0:00)', fuzzy=True)` solves the problem.
